/* objects.h — GENERATED by lvgl-web-designer — do not edit */
#pragma once
#include "ui_conf.h"

typedef struct {
    lv_obj_t * root;
    lv_obj_t * panel;
    lv_obj_t * title;
    lv_obj_t * btn_ok;
    lv_obj_t * sld;
    lv_obj_t * sw;
    lv_obj_t * cb;
    lv_obj_t * bar_dl;
    lv_obj_t * arc_vol;
    lv_obj_t * img_logo;
    lv_obj_t * dd;
    lv_obj_t * rl;
    lv_obj_t * ta;
    lv_obj_t * spin;
    lv_obj_t * qr;
    lv_obj_t * sc;
} ui_main_t;

extern ui_main_t ui_main;   /* 屏幕未创建时字段为 NULL */
