/* styles.c — GENERATED by lvgl-web-designer — do not edit */
#include "styles.h"

lv_style_t style_s_accent;
lv_style_t style_s_card;

void ui_styles_init(void)
{
    static bool inited = false;
    if(inited) return;
    inited = true;

    lv_style_init(&style_s_accent);
    lv_style_set_bg_color(&style_s_accent, UI_CONST_ACCENT);
    lv_style_set_radius(&style_s_accent, 8);
    lv_style_set_bg_opa(&style_s_accent, 204);

    lv_style_init(&style_s_card);
    lv_style_set_border_width(&style_s_card, 1);
    lv_style_set_border_color(&style_s_card, lv_color_hex(0x334455));
    lv_style_set_pad_all(&style_s_card, 12);
}
