/* objects.h — GENERATED by lvgl-web-designer — do not edit */
#pragma once
#include "ui_conf.h"

typedef struct {
    lv_obj_t * root;
    lv_obj_t * tv;
    lv_obj_t * tab_home;
    lv_obj_t * btn_go;
    lv_obj_t * sw_dark;
} ui_main_t;

extern ui_main_t ui_main;   /* 屏幕未创建时字段为 NULL */
