/* ui.h — GENERATED by lvgl-web-designer — do not edit */
#pragma once

#include "ui_conf.h"
#include "objects.h"
#include "styles.h"
#include "subjects.h"
#include "actions.h"
#include "screens/main.h"

void ui_init(void);        /* styles→subjects→入口屏创建并 lv_screen_load */
void ui_deinit(void);
