/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_lbl_left(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_label_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "lbl_left");
    #endif
    lv_obj_set_flex_grow(obj, 1);
    lv_label_set_text(obj, "L");
    return obj;
}

static lv_obj_t * create_lbl_right(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_label_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "lbl_right");
    #endif
    lv_obj_set_width(obj, LV_SIZE_CONTENT);
    lv_label_set_text(obj, "R");
    return obj;
}

static lv_obj_t * create_btn_a(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_a");
    #endif
    lv_obj_set_width(obj, lv_pct(50));
    lv_obj_set_height(obj, 40);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xffffff), LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_add_style(obj, &style_s_accent, LV_STATE_PRESSED);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_bg_color(root, lv_color_hex(0x101418), 0);
    lv_obj_set_style_pad_all(root, UI_CONST_GAP, 0);
    lv_obj_set_style_text_font(root, &lv_font_montserrat_14, 0);

    lv_obj_t * obj_1 = lv_obj_create(root);
    lv_obj_set_width(obj_1, lv_pct(100));
    lv_obj_set_height(obj_1, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(obj_1, LV_FLEX_FLOW_ROW);
    lv_obj_add_style(obj_1, &style_s_card, 0);
    ui_main.lbl_left = create_lbl_left(obj_1);
    ui_main.lbl_right = create_lbl_right(obj_1);
    ui_main.btn_a = create_btn_a(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
