/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_ln(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_line_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "ln");
    #endif
    static const lv_point_precise_t points_1[] = {{0, 0}, {50, 30}, {100, 0}, {150, 30}};
    lv_line_set_points(obj, points_1, 4);
    lv_line_set_y_invert(obj, true);
    lv_obj_set_style_line_width(obj, 4, 0);
    lv_obj_set_style_line_color(obj, lv_color_hex(0x00a2ff), 0);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.ln = create_ln(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
