/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_cv(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_canvas_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "cv");
    #endif
    LV_DRAW_BUF_DEFINE_STATIC(canvas_buf_1, 80, 60, LV_COLOR_FORMAT_ARGB8888);
    LV_DRAW_BUF_INIT_STATIC(canvas_buf_1);
    lv_canvas_set_draw_buf(obj, &canvas_buf_1);
    lv_canvas_fill_bg(obj, lv_color_hex(0x00c040), LV_OPA_COVER);
    lv_obj_set_width(obj, 80);
    lv_obj_set_height(obj, 60);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.cv = create_cv(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
