/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_sg(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_spangroup_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "sg");
    #endif
    lv_obj_set_width(obj, 200);
    lv_obj_set_height(obj, LV_SIZE_CONTENT);
    lv_spangroup_set_overflow(obj, LV_SPAN_OVERFLOW_ELLIPSIS);
    lv_spangroup_set_max_lines(obj, 3);
    lv_spangroup_set_indent(obj, 12);

    lv_span_t * spangroup_span_1 = lv_spangroup_add_span(obj);
    lv_spangroup_set_span_text(obj, spangroup_span_1, "Hello, ");

    lv_span_t * spangroup_span_2 = lv_spangroup_add_span(obj);
    lv_spangroup_set_span_text(obj, spangroup_span_2, "red");
    lv_spangroup_set_span_style(obj, spangroup_span_2, &style_s_red);

    lv_span_t * spangroup_span_3 = lv_spangroup_add_span(obj);
    lv_spangroup_bind_span_text(obj, spangroup_span_3, &subject_msg, "[%s]");
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.sg = create_sg(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
