/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_wnd(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_win_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "wnd");
    #endif
    lv_obj_set_width(obj, 240);
    lv_obj_set_height(obj, 200);
    lv_win_add_title(obj, "Window");

    lv_win_add_button(obj, &img_ico_close, 60);

    lv_win_add_button(obj, &img_ico_close, 40);

    lv_obj_t * label_1 = lv_label_create(obj);
    lv_obj_set_align(label_1, LV_ALIGN_CENTER);
    lv_label_set_text(label_1, "Body");
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.wnd = create_wnd(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
