/* subjects.c — GENERATED by lvgl-web-designer — do not edit */
#include "subjects.h"

lv_subject_t subject_msg;
static char subject_msg_buf[64];
static char subject_msg_prev_buf[64];

void ui_subjects_init(void)
{
    static bool inited = false;
    if(inited) return;
    inited = true;

    lv_subject_init_string(&subject_msg, subject_msg_buf, subject_msg_prev_buf, sizeof(subject_msg_buf), "hello");
}
