/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_cal(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_calendar_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "cal");
    #endif
    lv_obj_set_width(obj, 230);
    lv_obj_set_height(obj, 230);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_calendar_set_today_year(obj, 2026);
    lv_calendar_set_today_month(obj, 7);
    lv_calendar_set_today_day(obj, 2);
    lv_calendar_set_shown_year(obj, 2026);
    lv_calendar_set_shown_month(obj, 7);

    lv_calendar_add_header_arrow(obj);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.cal = create_cal(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
