/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_btn_open(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_list_add_button(parent, &img_ico_file, "Open");
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_open");
    #endif
    return obj;
}

static lv_obj_t * create_lst(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_list_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "lst");
    #endif
    lv_obj_set_width(obj, 200);
    lv_obj_set_height(obj, 200);

    lv_list_add_text(obj, "Files");
    ui_main.btn_open = create_btn_open(obj);

    lv_list_add_button(obj, NULL, "About");
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.lst = create_lst(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
