/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_mn(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_menu_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "mn");
    #endif
    lv_obj_set_width(obj, 200);
    lv_obj_set_height(obj, 200);
    lv_menu_set_mode_root_back_button(obj, LV_MENU_ROOT_BACK_BUTTON_ENABLED);

    lv_obj_t * menu_page_1 = lv_menu_page_create(obj, "Main");
    lv_menu_set_page(obj, menu_page_1);

    lv_obj_t * label_2 = lv_label_create(menu_page_1);
    lv_label_set_text(label_2, "Item 1");

    lv_obj_t * menu_page_3 = lv_menu_page_create(obj, NULL);

    lv_obj_t * label_4 = lv_label_create(menu_page_3);
    lv_label_set_text(label_4, "Item 2");
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.mn = create_mn(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
