/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_ch(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_chart_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "ch");
    #endif
    lv_obj_set_width(obj, 200);
    lv_obj_set_height(obj, 150);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_chart_set_point_count(obj, 8);
    lv_chart_set_update_mode(obj, LV_CHART_UPDATE_MODE_CIRCULAR);
    lv_chart_set_hor_div_line_count(obj, 4);

    lv_chart_series_t * chart_series_1 = lv_chart_add_series(obj, lv_color_hex(0xff0000), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_next_value(obj, chart_series_1, 10);
    lv_chart_set_next_value(obj, chart_series_1, 20);
    lv_chart_set_next_value(obj, chart_series_1, 30);
    lv_chart_set_next_value(obj, chart_series_1, 25);
    lv_chart_set_next_value(obj, chart_series_1, 40);
    lv_chart_set_next_value(obj, chart_series_1, 35);
    lv_chart_set_next_value(obj, chart_series_1, 50);
    lv_chart_set_next_value(obj, chart_series_1, 45);

    lv_chart_series_t * chart_series_2 = lv_chart_add_series(obj, lv_color_hex(0x00c040), LV_CHART_AXIS_SECONDARY_Y);
    lv_chart_set_next_value(obj, chart_series_2, 5);
    lv_chart_set_next_value(obj, chart_series_2, 15);
    lv_chart_set_next_value(obj, chart_series_2, 10);
    lv_chart_set_next_value(obj, chart_series_2, 20);
    lv_chart_set_next_value(obj, chart_series_2, 15);
    lv_chart_set_next_value(obj, chart_series_2, 25);
    lv_chart_set_next_value(obj, chart_series_2, 20);
    lv_chart_set_next_value(obj, chart_series_2, 30);

    lv_chart_cursor_t * chart_cursor_3 = lv_chart_add_cursor(obj, lv_color_hex(0x0000ff), LV_DIR_VER);
    lv_chart_set_cursor_pos_x(obj, chart_cursor_3, 3);
    lv_chart_set_cursor_pos_y(obj, chart_cursor_3, 20);

    lv_chart_set_axis_min_value(obj, LV_CHART_AXIS_SECONDARY_Y, 0);
    lv_chart_set_axis_max_value(obj, LV_CHART_AXIS_SECONDARY_Y, 60);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.ch = create_ch(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
