/* ui_conf.h — GENERATED by lvgl-web-designer — do not edit */
#pragma once

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

/* 回调 weak 兜底(actions_default.c 用)。无 weak 的编译器定义 UI_NO_WEAK,
 * 兜底整体停用,全部回调必须在 actions.c 自行实现(见 INTEGRATION.md)。 */
#if defined(__GNUC__) || defined(__clang__)
#define UI_WEAK __attribute__((weak))
#elif defined(__ICCARM__)
#define UI_WEAK __weak
#else
#define UI_WEAK
#define UI_NO_WEAK 1
#endif
