/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static void screen_evt_1_cb(lv_event_t * e)
{
    LV_UNUSED(e);
    lv_screen_load_anim(ui_settings_create(), LV_SCREEN_LOAD_ANIM_OVER_RIGHT, 300, 0, false);
}

static lv_obj_t * create_arc_vol(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_arc_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "arc_vol");
    #endif
    lv_obj_set_width(obj, 400);
    lv_obj_set_height(obj, 400);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_arc_bind_value(obj, &subject_volume);
    return obj;
}

static lv_obj_t * create_lbl_vol(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_label_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "lbl_vol");
    #endif
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_label_bind_text(obj, &subject_volume, "Vol: %d");
    lv_obj_bind_flag_if_gt(obj, &subject_volume, LV_OBJ_FLAG_HIDDEN, 90);
    return obj;
}

static lv_obj_t * create_sw_mute(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_switch_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "sw_mute");
    #endif
    lv_obj_set_y(obj, -40);
    lv_obj_set_align(obj, LV_ALIGN_BOTTOM_MID);
    lv_obj_bind_checked(obj, &subject_muted);
    return obj;
}

static lv_obj_t * create_btn_up(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_up");
    #endif
    lv_obj_set_x(obj, 20);
    lv_obj_set_y(obj, 20);
    lv_obj_bind_state_if_ge(obj, &subject_volume, LV_STATE_DISABLED, 100);
    lv_subject_increment_dsc_t * inc_1 = lv_obj_add_subject_increment_event(obj, &subject_volume, LV_EVENT_CLICKED, 5);
    lv_obj_set_subject_increment_event_min_value(obj, inc_1, 0);
    lv_obj_set_subject_increment_event_max_value(obj, inc_1, 100);
    lv_obj_set_subject_increment_event_rollover(obj, inc_1, false);
    lv_obj_add_event_cb(obj, on_up_long, LV_EVENT_LONG_PRESSED, "fast");
    return obj;
}

static lv_obj_t * create_btn_reset(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_reset");
    #endif
    lv_obj_set_x(obj, 20);
    lv_obj_set_y(obj, 80);
    lv_obj_add_subject_set_int_event(obj, &subject_volume, LV_EVENT_CLICKED, 30);
    lv_obj_add_subject_toggle_event(obj, &subject_muted, LV_EVENT_DOUBLE_CLICKED);
    return obj;
}

static lv_obj_t * create_btn_settings(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_settings");
    #endif
    lv_obj_set_x(obj, 20);
    lv_obj_set_y(obj, 140);
    lv_obj_add_event_cb(obj, screen_evt_1_cb, LV_EVENT_CLICKED, NULL);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 466);
    lv_obj_set_height(root, 466);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    lv_obj_set_style_bg_color(root, lv_color_hex(0x000000), 0);
    ui_main.arc_vol = create_arc_vol(root);
    ui_main.lbl_vol = create_lbl_vol(root);
    ui_main.sw_mute = create_sw_mute(root);
    ui_main.btn_up = create_btn_up(root);
    ui_main.btn_reset = create_btn_reset(root);
    ui_main.btn_settings = create_btn_settings(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
