/* screens/settings.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_settings_t ui_settings;

static void screen_evt_1_cb(lv_event_t * e)
{
    LV_UNUSED(e);
    lv_screen_load_anim(ui_main_create(), LV_SCREEN_LOAD_ANIM_FADE_IN, 200, 0, false);
}

static lv_obj_t * create_lbl_msg(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_label_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "lbl_msg");
    #endif
    lv_label_bind_text(obj, &subject_msg, NULL);
    return obj;
}

static lv_obj_t * create_btn_back(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_back");
    #endif
    lv_obj_set_align(obj, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_event_cb(obj, screen_evt_1_cb, LV_EVENT_CLICKED, NULL);
    return obj;
}

lv_obj_t * ui_settings_create(void)
{
    if(ui_settings.root) return ui_settings.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_settings.root = root;
    lv_obj_set_width(root, 466);
    lv_obj_set_height(root, 466);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "settings");
    #endif
    ui_settings.lbl_msg = create_lbl_msg(root);
    ui_settings.btn_back = create_btn_back(root);
    return root;
}

void ui_settings_destroy(void)
{
    if(!ui_settings.root) return;
    lv_obj_delete(ui_settings.root);
    lv_memzero(&ui_settings, sizeof(ui_settings));
}
