/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_arcl(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_arclabel_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "arcl");
    #endif
    lv_obj_set_width(obj, 150);
    lv_obj_set_height(obj, 150);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_arclabel_set_text(obj, "Curved Text");
    lv_arclabel_set_angle_start(obj, 90);
    lv_arclabel_set_angle_size(obj, 270);
    lv_arclabel_set_offset(obj, 5);
    lv_arclabel_set_dir(obj, LV_ARCLABEL_DIR_COUNTER_CLOCKWISE);
    lv_arclabel_set_recolor(obj, true);
    lv_arclabel_set_radius(obj, 70);
    lv_arclabel_set_center_offset_x(obj, 2);
    lv_arclabel_set_center_offset_y(obj, -2);
    lv_arclabel_set_text_vertical_align(obj, LV_ARCLABEL_TEXT_ALIGN_CENTER);
    lv_arclabel_set_text_horizontal_align(obj, LV_ARCLABEL_TEXT_ALIGN_CENTER);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.arcl = create_arcl(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
