/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_btn_go(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_go");
    #endif
    lv_obj_set_width(obj, 80);
    lv_obj_set_height(obj, 30);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);

    lv_obj_t * label_1 = lv_label_create(obj);
    lv_obj_set_align(label_1, LV_ALIGN_CENTER);
    lv_label_set_text(label_1, "Go");
    return obj;
}

static lv_obj_t * create_tab_home(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_tabview_add_tab(parent, "Home");
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "tab_home");
    #endif

    lv_obj_t * label_1 = lv_label_create(obj);
    lv_obj_set_align(label_1, LV_ALIGN_TOP_MID);
    lv_label_set_text(label_1, "Welcome");
    ui_main.btn_go = create_btn_go(obj);
    return obj;
}

static lv_obj_t * create_sw_dark(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_switch_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "sw_dark");
    #endif
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    return obj;
}

static lv_obj_t * create_tv(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_tabview_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "tv");
    #endif
    lv_obj_set_width(obj, 240);
    lv_obj_set_height(obj, 320);
    lv_tabview_set_active(obj, 1, LV_ANIM_OFF);
    lv_tabview_set_tab_bar_position(obj, LV_DIR_BOTTOM);
    ui_main.tab_home = create_tab_home(obj);

    lv_obj_t * tabview_tab_1 = lv_tabview_add_tab(obj, "Settings");
    ui_main.sw_dark = create_sw_dark(tabview_tab_1);

    lv_obj_t * tabview_tab_bar_2 = lv_tabview_get_tab_bar(obj);
    lv_obj_set_style_bg_color(tabview_tab_bar_2, lv_color_hex(0x202030), 0);

    lv_obj_t * tabview_tab_button_3 = lv_tabview_get_tab_button(obj, 0);
    lv_obj_set_style_text_color(tabview_tab_button_3, lv_color_hex(0xffcc00), 0);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.tv = create_tv(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
