/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_bm(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_buttonmatrix_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "bm");
    #endif
    lv_obj_set_width(obj, 220);
    lv_obj_set_height(obj, 140);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    static const char * map_1[] = {"1", "2", "3", "\n", "OK", "Cancel", ""};
    lv_buttonmatrix_set_map(obj, map_1);
    lv_buttonmatrix_set_button_ctrl(obj, 0, LV_BUTTONMATRIX_CTRL_WIDTH_1);
    lv_buttonmatrix_set_button_ctrl(obj, 1, LV_BUTTONMATRIX_CTRL_WIDTH_1);
    lv_buttonmatrix_set_button_ctrl(obj, 2, LV_BUTTONMATRIX_CTRL_WIDTH_1);
    lv_buttonmatrix_set_button_ctrl(obj, 3, LV_BUTTONMATRIX_CTRL_CHECKABLE | LV_BUTTONMATRIX_CTRL_CHECKED);
    lv_buttonmatrix_set_button_ctrl(obj, 4, LV_BUTTONMATRIX_CTRL_DISABLED);
    lv_buttonmatrix_set_selected_button(obj, 1);
    lv_buttonmatrix_set_one_checked(obj, true);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.bm = create_bm(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
