/**
 * C(LVGL 9.4)emitter:src/ui/ 目录布局(design/03 §3,ARCHITECTURE §3.6)。
 * - actions 分文件 + weak 兜底;actions.c 标 overwrite:false(write-if-absent)
 * - lv_obj_set_name 一律包 #if LV_USE_OBJ_NAME(评审 R8 定案)
 * - create 函数体顺序固定:create → set_name → props → flags/states →
 *   inline styles → add_style → bindings → events → children → cPatch(仅 9.4 历史兼容)
 */
import {
  M1_TEXT_FONTS, OBJ_BASE, STYLE_PROPS,
  constMacroName, formatEnumForC, formatValueForC, isConstRef,
  type CName, type ConstDef, type LvProject, type PropSpec, type PropValue,
  type Selector, type SubjectDef,
} from '@lvd/schema';
import type { BuildTarget, ColorFormat, DisplayRef } from '@lvd/schema/v2';
import {
  normalizeProject,
  type Diagnostic, type IREvent, type IRNamedStyle, type IRNode, type IRProject, type IRScreen,
} from '@lvd/compiler-core';
import {
  collectRequirements, integrationMd, requirementsTxt, type LvglCVersion,
} from './requirements.js';

export interface GeneratedFile {
  path: string;                     // 相对 src/ui/
  content: string;
  overwrite?: boolean;              // false = write-if-absent(actions.c)
}

/** 导出目标:esp-idf(组件 CMakeLists,默认)/ cmake(通用)/ bare(无构建文件) */
export type CTarget = 'esp-idf' | 'cmake' | 'bare';

export interface EmitC94Options {
  target?: CTarget;                 // 缺省 'esp-idf'(保持既有行为)
  /** 9.5 发布目标的实际 Display Color Format；v1 16bpp 不允许静默猜测。 */
  colorFormat?: ColorFormat;
  /** Designer 发布链锁定的完整 Schema v2 BuildTarget 快照。 */
  buildTarget?: BuildTarget;
  /** BuildTarget 经 Controller 间接引用的 DisplayProfile 快照。 */
  displayProfileRef?: DisplayRef;
}

/** 共享 C emitter 实现的精确目标版本。 */
export type CEmitterVersion = LvglCVersion;

export interface CEmitResult {
  files: GeneratedFile[];
  diagnostics: Diagnostic[];
}

const GEN_HEADER = '/* GENERATED by lvgl-web-designer — do not edit */';

/* ---------------------------------------------------------------- 值格式化 */

/** 资产引用的 C 符号约定:图片 img_<name>、自定义字体 font_<name>、内置 lv_font_montserrat_N */
function cAssetRef(value: PropValue, type: 'imageRef' | 'fontRef'): string {
  if (isConstRef(value)) return constMacroName(value.$const);
  const name = String(value);
  if (type === 'fontRef') {
    return M1_TEXT_FONTS.includes(name) ? `&lv_font_${name}` : `&font_${name}`;
  }
  return `&img_${name}`;
}

function cValue(
  value: PropValue,
  spec: { type: PropSpec['type'] | 'gradRef'; enum?: PropSpec['enum'] },
): string {
  if (spec.type === 'imageRef' || spec.type === 'fontRef') {
    return cAssetRef(value, spec.type);
  }
  if (spec.type === 'gradRef') return `&grad_${String(value)}`;   // 渐变二期,占位约定
  if (spec.type === 'subject') return `&subject_${String(value)}`;
  if (spec.type === 'styleRef') return `&style_${String(value)}`;
  if (spec.type === 'orFlags') {
    // 'a|b' → PREFIX_A | PREFIX_B(单组;buttonmatrix ctrl_map 的多组走 $idx/$ored)
    return String(value)
      .split('|')
      .map((t) => formatEnumForC(t.trim(), spec.enum))
      .join(' | ');
  }
  return formatValueForC(value, { type: spec.type, enum: spec.enum });
}

/** LV_PART_* | LV_STATE_*;空 selector → 0(part 在前,design/01 §4.3) */
function cSelector(sel: Selector | undefined): string {
  const parts: string[] = [];
  if (sel?.part && sel.part !== 'main') parts.push(`LV_PART_${sel.part.toUpperCase()}`);
  for (const s of sel?.states ?? []) {
    if (s !== 'default') parts.push(`LV_STATE_${s.toUpperCase()}`);
  }
  return parts.length > 0 ? parts.join(' | ') : '0';
}

function cTrigger(trigger: string): string {
  return `LV_EVENT_${trigger.toUpperCase()}`;
}

function cScreenAnim(anim: string | undefined): string {
  return `LV_SCREEN_LOAD_ANIM_${(anim ?? 'none').toUpperCase()}`;
}

interface SetterEnv {
  objExpr: string;                  // $obj:本节点句柄(virtual 子元素无)
  parentExpr: string;               // $parent:父 widget 句柄(chart/table/spangroup 等)
  node: IRNode;
  screenName: string;               // $ref:同 screen 命名 widget → ui_<screen>.<name>
  emitted: Set<string>;             // 无 $v 模板的去重域(spinner 合一 setter / imagebutton 按 state 聚合)
}

/**
 * setter 模板展开:
 * $obj / $parent / $v / $ref(widget 名引用)
 * $<createProp>(构造实参,如 $row/$column/$axis)
 * $<companion>:<T>:<F>(bool 三目)/ $<companion>(枚举取 token;string 引号化,缺省 NULL)
 */
function expandSetter(
  template: string,
  valueExpr: string,
  spec: PropSpec,
  env: SetterEnv,
): string {
  const { node } = env;
  return template.replace(
    /\$([a-z_][a-z0-9_]*)(?::([A-Za-z_0-9]+):([A-Za-z_0-9]+))?/g,
    (_m, name: string, t?: string, f?: string) => {
      if (name === 'obj') return env.objExpr;
      if (name === 'parent') return env.parentExpr;
      if (name === 'v') return valueExpr;
      if (name === 'ref') return `ui_${env.screenName}.${String(node.props[spec.key])}`;
      if (t !== undefined && f !== undefined) {
        return node.props[name] === true ? t : f;
      }
      const createSpec = node.createPropSpecs.find((c) => c.key === name);
      if (createSpec) {
        const v = node.props[name] ?? createSpec.default;
        return v === undefined ? '0' : cValue(v, createSpec);
      }
      const comp = spec.companions?.find((c) => c.key === name);
      if (comp?.enum) {
        const token = String(node.props[name] ?? comp.enum.tokens[0]);
        return formatEnumForC(token, comp.enum);
      }
      if (comp?.type === 'string') {
        const v = node.props[name];
        return v === undefined ? 'NULL' : formatValueForC(v, { type: 'string' });
      }
      // 兄弟专有属性(spinner 合一 setter 的 $anim_duration/$angle、
      // imagebutton 按 state 聚合的 $src_*):值缺省取 registry default;
      // 无 default 的指针类(imageRef/string)发 NULL
      const sibling = node.ownPropSpecs.find((p) => p.key === name);
      if (sibling) {
        const v = node.props[name] ?? sibling.default;
        if (v === undefined) {
          return sibling.type === 'imageRef' || sibling.type === 'string' ? 'NULL' : '0';
        }
        return cValue(v, sibling);
      }
      return String(node.props[name] ?? '0');
    },
  );
}

/**
 * cCreate 模板展开:$parent + $<createProp>(实参来自 createProps,缺省取 default)。
 * 'lv_chart_add_series($parent, $color, $axis)' →
 * 'lv_chart_add_series(obj, lv_color_hex(0xff0000), LV_CHART_AXIS_PRIMARY_Y)'
 */
function expandCreate(node: IRNode, parentExpr: string): string {
  return node.cCreate.replace(/\$([a-z_][a-z0-9_]*)/g, (m, name: string) => {
    if (name === 'parent') return parentExpr;
    const cp = node.createPropSpecs.find((c) => c.key === name);
    if (cp) {
      const v = node.props[cp.key] ?? cp.default;
      if (v === undefined) {
        // optional 指针实参(menu-page title / list-button·win-button icon)缺省 NULL
        return cp.type === 'string' || cp.type === 'imageRef' ? 'NULL' : '0';
      }
      return cValue(v, cp);
    }
    return m;
  });
}

/* ------------------------------------------------------------------ consts */

function constDefine(c: ConstDef): string {
  let v: string;
  switch (c.type) {
    case 'color': v = `lv_color_hex(0x${c.value.replace(/^#/, '').replace(/^0x/i, '')})`; break;
    case 'string': v = JSON.stringify(c.value); break;
    case 'percent': v = `lv_pct(${c.value.replace(/%$/, '')})`; break;
    default: v = c.value;                    // int / px
  }
  return `#define ${constMacroName(c.name)} ${v}`;
}

/* ----------------------------------------------------------------- writer */

class CWriter {
  private lines: string[] = [];
  private depth = 0;
  push(text = ''): void {
    this.lines.push(text === '' ? '' : `${'    '.repeat(this.depth)}${text}`);
  }
  open(text: string): void { this.push(text); this.push('{'); this.depth++; }
  close(): void { this.depth--; this.push('}'); }
  toString(): string { return `${this.lines.join('\n')}\n`; }
}

/* ------------------------------------------------------------- 屏幕编译单元 */

interface ScreenGenCtx {
  ir: IRProject;
  screen: IRScreen;
  diags: Diagnostic[];
  trampolines: string[];            // screen_load/create 事件跳板函数定义
  trampolineN: number;
  callbacks: Set<CName>;            // 全工程回调收集(actions.h)
  allowLegacyCPatch: boolean;       // 仅 9.4 旧工程兼容;9.5 发布必须阻断任意 C
}

/** prop 绑定 → C API(9.4 头文件核对) */
const PROP_BIND_FN: Record<string, Record<string, string>> = {
  value: {
    slider: 'lv_slider_bind_value', bar: 'lv_bar_bind_value', arc: 'lv_arc_bind_value',
    dropdown: 'lv_dropdown_bind_value', roller: 'lv_roller_bind_value', spinbox: 'lv_spinbox_bind_value',
  },
};

/**
 * 单属性 setter 输出,含五种特殊模板:
 * - $each(intList):逐元素一行(chart series values → set_next_value)
 * - $strarr(stringQuotedList):static const char * 数组 + 调用(buttonmatrix map)
 * - $idx/$ored(orFlags 空格分组):逐按钮位或调用(buttonmatrix ctrl_map)
 * - $ptarr/$n(pointList):static lv_point_precise_t 数组 + 调用(line points)
 * - $imgarr/$n(stringList of imageRef):static const void * 数组 + 调用(animimg srcs)
 * 另:空模板跳过(widget 级特殊形态处理,如 lottie src);
 * 无 $v 模板按展开结果去重(spinner/imagebutton 多属性合一 setter),bool false 不发。
 */
function emitPropSetter(
  spec: PropSpec,
  v: PropValue,
  w: CWriter,
  env: SetterEnv,
  localCounter: { n: number },
): void {
  const tpl = spec.c.setter;
  if (tpl === '') return;
  if (tpl.includes('$ptarr')) {
    const nums = (Array.isArray(v) ? v : []).map(Number);
    const pairs: string[] = [];
    for (let i = 0; i + 1 < nums.length; i += 2) pairs.push(`{${nums[i]}, ${nums[i + 1]}}`);
    const arr = `points_${++localCounter.n}`;
    w.push(`static const lv_point_precise_t ${arr}[] = {${pairs.join(', ')}};`);
    const t = tpl.replace('$ptarr', arr).replace('$n', String(pairs.length));
    w.push(`${expandSetter(t, '', spec, env)};`);
    return;
  }
  if (tpl.includes('$imgarr')) {
    const names = (Array.isArray(v) ? v : [v]).map(String).filter(Boolean);
    const arr = `srcs_${++localCounter.n}`;
    w.push(`static const void * ${arr}[] = {${names.map((s) => `&img_${s}`).join(', ')}};`);
    const t = tpl.replace('$imgarr', arr).replace('$n', String(names.length));
    w.push(`${expandSetter(t, '', spec, env)};`);
    return;
  }
  if (tpl.includes('$strarr')) {
    const items = (Array.isArray(v) ? v : [v])
      .map((s) => formatValueForC(s as PropValue, { type: 'string' }));
    const arr = `map_${++localCounter.n}`;
    w.push(`static const char * ${arr}[] = {${[...items, '""'].join(', ')}};`);
    w.push(`${expandSetter(tpl.replace('$strarr', arr), '', spec, env)};`);
    return;
  }
  if (tpl.includes('$idx') && tpl.includes('$ored')) {
    const groups = String(v).trim().split(/\s+/).filter(Boolean);
    groups.forEach((group, idx) => {
      const ored = group
        .split('|')
        .map((t) => formatEnumForC(t.trim(), spec.enum))
        .join(' | ');
      w.push(`${expandSetter(tpl.replace('$idx', String(idx)).replace('$ored', ored), '', spec, env)};`);
    });
    return;
  }
  if (tpl.includes('$each')) {
    const items = Array.isArray(v) ? v : String(v).trim().split(/\s+/).map(Number);
    for (const item of items) {
      w.push(`${expandSetter(tpl.replace('$each', String(item)), '', spec, env)};`);
    }
    return;
  }
  if (!tpl.includes('$v')) {
    // 无参/合一 setter:bool 开关 false 不发(如 msgbox close_button);
    // 相同展开只发一次(spinner anim_params、imagebutton 同 state 三段)
    if (spec.type === 'bool' && v === false) return;
    const line = `${expandSetter(tpl, '', spec, env)};`;
    if (env.emitted.has(line)) return;
    env.emitted.add(line);
    w.push(line);
    return;
  }
  w.push(`${expandSetter(tpl, cValue(v, spec), spec, env)};`);
}

/**
 * canvas / lottie 特殊形态(manifest notes):
 * - canvas:LV_DRAW_BUF_DEFINE_STATIC(ARGB8888)+ set_draw_buf + fill_bg
 *   (fill_color 缺省 #ffffff,与自研 parser 默认一致;该 prop 标记 handled)
 * - lottie:static uint8_t 渲染缓冲 + lv_lottie_set_buffer;
 *   src → lv_lottie_set_src_data(extern 数组,符号 lottie_<name>[]/_size,如 xxd -i 生成)
 * width/height 只认纯 px,非纯 px 告警并按 100 处理。
 */
function emitDrawBufWidget(
  node: IRNode,
  objExpr: string,
  w: CWriter,
  ctx: ScreenGenCtx,
  localCounter: { n: number },
  handled: Set<string>,
): void {
  const px = (key: 'width' | 'height'): number => {
    const raw = node.props[key];
    if (typeof raw === 'number' && Number.isFinite(raw)) return raw;
    if (raw !== undefined) {
      ctx.diags.push({
        severity: 'warning', code: 'W_NON_PX_BUF_SIZE',
        message: `${node.type}.${key} 仅支持纯 px,绘制缓冲按 100 处理:${JSON.stringify(raw)}`,
        nodeId: node.id,
      });
    }
    return 100;
  };
  const bw = px('width');
  const bh = px('height');

  if (node.type === 'canvas') {
    const buf = `canvas_buf_${++localCounter.n}`;
    w.push(`LV_DRAW_BUF_DEFINE_STATIC(${buf}, ${bw}, ${bh}, LV_COLOR_FORMAT_ARGB8888);`);
    w.push(`LV_DRAW_BUF_INIT_STATIC(${buf});`);
    w.push(`lv_canvas_set_draw_buf(${objExpr}, &${buf});`);
    const fill = node.props['fill_color'] ?? '#ffffff';
    w.push(`lv_canvas_fill_bg(${objExpr}, ${cValue(fill, { type: 'color' })}, LV_OPA_COVER);`);
    handled.add('fill_color');
    return;
  }

  /* lottie */
  const buf = `lottie_buf_${++localCounter.n}`;
  w.push(`static uint8_t ${buf}[${bw} * ${bh} * 4];   /* ARGB8888 渲染缓冲 */`);
  w.push(`lv_lottie_set_buffer(${objExpr}, ${bw}, ${bh}, ${buf});`);
  const src = node.props['src'];
  if (src !== undefined) {
    const name = String(isConstRef(src) ? src.$const : src);
    w.push(`/* TODO: 提供动画数据符号(如 xxd -i ${name}.json 生成,符号名改成下面两个) */`);
    w.push(`extern const uint8_t lottie_${name}[];`);
    w.push(`extern const size_t lottie_${name}_size;`);
    w.push(`lv_lottie_set_src_data(${objExpr}, lottie_${name}, lottie_${name}_size);`);
  }
  handled.add('src');
}

function emitNodeBody(
  node: IRNode,
  objExpr: string,
  parentExpr: string,
  w: CWriter,
  ctx: ScreenGenCtx,
  localCounter: { n: number },
  isRoot: boolean,
): void {
  const env: SetterEnv = {
    objExpr, parentExpr, node, screenName: ctx.screen.name, emitted: new Set(),
  };

  /* ---- name(宏守卫,评审 R8) */
  if (node.named) {
    w.push('#if LV_USE_OBJ_NAME');
    w.push(`lv_obj_set_name(${objExpr}, "${node.name}");`);
    w.push('#endif');
  }

  /* ---- 自研控件特殊形态(manifest notes):canvas / lottie 的静态绘制缓冲 */
  const handled = new Set<string>();
  if (node.type === 'canvas' || node.type === 'lottie') {
    emitDrawBufWidget(node, objExpr, w, ctx, localCounter, handled);
  }

  /* ---- props(objBase → 专有,registry 顺序;root 的 width/height 由 display 尺寸决定;
   *      createProps 已在 create 实参消费,不再 setter) */
  const specs = node.useObjBase ? [...OBJ_BASE.props, ...node.ownPropSpecs] : [...node.ownPropSpecs];
  for (const spec of specs) {
    if (isRoot && (spec.key === 'width' || spec.key === 'height')) continue;
    if (handled.has(spec.key)) continue;
    const v = node.props[spec.key];
    if (v === undefined) continue;
    emitPropSetter(spec, v, w, env, localCounter);
  }

  /* ---- animimage:有帧序列则自动起播(与自研 parser 同语义) */
  if (node.type === 'animimage' && node.props['srcs'] !== undefined) {
    w.push(`lv_animimg_start(${objExpr});`);
  }

  /* ---- flags / states */
  for (const [f, v] of node.flags) {
    w.push(`lv_obj_set_flag(${objExpr}, LV_OBJ_FLAG_${f.toUpperCase()}, ${v ? 'true' : 'false'});`);
  }
  for (const [s, v] of node.states) {
    w.push(`lv_obj_set_state(${objExpr}, LV_STATE_${s.toUpperCase()}, ${v ? 'true' : 'false'});`);
  }

  /* ---- inline styles */
  for (const g of node.inlineStyles) {
    const sel = cSelector(g.selector);
    for (const [k, v] of Object.entries(g.props)) {
      const sp = STYLE_PROPS[k];
      if (!sp) continue;
      w.push(`lv_obj_set_style_${sp.cSuffix}(${objExpr}, ${cValue(v, sp)}, ${sel});`);
    }
  }

  /* ---- 命名样式 */
  for (const u of node.styleUses) {
    w.push(`lv_obj_add_style(${objExpr}, &style_${u.styleName}, ${cSelector(u.selector)});`);
  }

  /* ---- 绑定 */
  for (const b of node.bindings) {
    if (b.kind === 'prop') {
      if (b.prop === 'checked') {
        w.push(`lv_obj_bind_checked(${objExpr}, &subject_${b.subject});`);
      } else if (b.prop === 'text') {
        const fmt = b.fmt !== undefined ? JSON.stringify(b.fmt) : 'NULL';
        w.push(`lv_label_bind_text(${objExpr}, &subject_${b.subject}, ${fmt});`);
      } else if (b.prop === 'src') {
        w.push(`lv_image_bind_src(${objExpr}, &subject_${b.subject});`);
      } else {
        const fn = PROP_BIND_FN[b.prop]?.[node.type];
        if (!fn) {
          ctx.diags.push({
            severity: 'warning', code: 'W_UNSUPPORTED_BINDING',
            message: `C 通道暂不支持 ${node.type}.bind_${b.prop},已跳过`, nodeId: node.id,
          });
          continue;
        }
        w.push(`${fn}(${objExpr}, &subject_${b.subject});`);
      }
    } else if (b.kind === 'flag') {
      w.push(`lv_obj_bind_flag_if_${b.op}(${objExpr}, &subject_${b.subject}, LV_OBJ_FLAG_${b.flag.toUpperCase()}, ${b.refValue});`);
    } else {
      w.push(`lv_obj_bind_state_if_${b.op}(${objExpr}, &subject_${b.subject}, LV_STATE_${b.state.toUpperCase()}, ${b.refValue});`);
    }
  }

  /* ---- 事件 */
  for (const e of node.events) emitEvent(e, objExpr, w, ctx, localCounter);

  /* ---- 子节点(ChildSpec 三形态:add/getter 得句柄,virtual 直调父) */
  // menu:首个 page 自动 lv_menu_set_page(与自研 parser 同语义,预览可见)
  let menuPagePending = node.type === 'menu';
  for (const child of node.children) {
    if (child.childKind === 'virtual') {
      // 无对象:属性是 "(行,列)=值" 式调用,$parent 即本节点
      const childEnv: SetterEnv = {
        objExpr: '', parentExpr: objExpr, node: child,
        screenName: ctx.screen.name, emitted: new Set(),
      };
      w.push('');
      for (const spec of child.ownPropSpecs) {
        const v = child.props[spec.key];
        if (v === undefined) continue;
        emitPropSetter(spec, v, w, childEnv, localCounter);
      }
      continue;
    }
    const isFirstMenuPage = menuPagePending && child.type === 'menu-page';
    if (isFirstMenuPage) menuPagePending = false;
    if (child.named) {
      // 命名节点独立 create 函数;调用点回填 objects 结构体
      w.push(`ui_${ctx.screen.name}.${child.name} = create_${child.name}(${objExpr});`);
      if (isFirstMenuPage) {
        w.push(`lv_menu_set_page(${objExpr}, ui_${ctx.screen.name}.${child.name});`);
      }
      continue;
    }
    // add/getter(或普通 widget):句柄类型缺省 lv_obj_t *
    const needsHandle = isFirstMenuPage || Object.keys(child.props).some(
      (k) => !child.createPropSpecs.some((cp) => cp.key === k),
    ) || child.flags.length > 0 || child.states.length > 0
      || child.inlineStyles.length > 0 || child.styleUses.length > 0
      || child.bindings.length > 0 || child.events.length > 0
      || child.children.length > 0 || child.cPatch?.post !== undefined;
    w.push('');
    if (!needsHandle) {
      w.push(`${expandCreate(child, objExpr)};`);       // 句柄无人用,免 -Wunused
      continue;
    }
    const local = `${child.type.replace(/-/g, '_')}_${++localCounter.n}`;
    w.push(`${child.cHandleType ?? 'lv_obj_t *'} ${local} = ${expandCreate(child, objExpr)};`);
    if (isFirstMenuPage) w.push(`lv_menu_set_page(${objExpr}, ${local});`);
    emitNodeBody(child, local, objExpr, w, ctx, localCounter, false);
  }

  /* ---- cPatch：仅 9.4 历史兼容通道可发；9.5 普通发布严禁透传任意 C */
  if (node.cPatch?.post) {
    if (ctx.allowLegacyCPatch) {
      w.push(`/* USER-PATCH ${node.id} BEGIN */`);
      for (const line of node.cPatch.post.replace(/\$obj/g, objExpr).split('\n')) w.push(line);
      w.push(`/* USER-PATCH ${node.id} END */`);
    } else {
      ctx.diags.push({
        severity: 'error',
        code: 'E_CPATCH_FORBIDDEN',
        message: 'LVGL 9.5 普通发布禁止 cPatch；请改为 typed property，或通过独立 trusted extension 审批链处理',
        nodeId: node.id,
      });
    }
  }
}

function emitEvent(
  e: IREvent,
  objExpr: string,
  w: CWriter,
  ctx: ScreenGenCtx,
  localCounter: { n: number },
): void {
  const trig = cTrigger(e.trigger);
  switch (e.kind) {
    case 'callback': {
      ctx.callbacks.add(e.callback);
      const ud = e.userData !== undefined ? JSON.stringify(e.userData) : 'NULL';
      w.push(`lv_obj_add_event_cb(${objExpr}, ${e.callback}, ${trig}, ${ud});`);
      break;
    }
    case 'subject_set': {
      let v: string;
      if (e.subjectType === 'int') v = String(parseInt(e.value, 10) || 0);
      else if (e.subjectType === 'float') v = `${Number(e.value) || 0}f`;
      else v = JSON.stringify(e.value);
      w.push(`lv_obj_add_subject_set_${e.subjectType}_event(${objExpr}, &subject_${e.subject}, ${trig}, ${v});`);
      break;
    }
    case 'subject_toggle':
      w.push(`lv_obj_add_subject_toggle_event(${objExpr}, &subject_${e.subject}, ${trig});`);
      break;
    case 'subject_increment': {
      const step = e.step ?? 1;
      if (e.min === undefined && e.max === undefined && e.rollover === undefined) {
        w.push(`lv_obj_add_subject_increment_event(${objExpr}, &subject_${e.subject}, ${trig}, ${step});`);
      } else {
        const dsc = `inc_${++localCounter.n}`;
        w.push(`lv_subject_increment_dsc_t * ${dsc} = lv_obj_add_subject_increment_event(${objExpr}, &subject_${e.subject}, ${trig}, ${step});`);
        if (e.min !== undefined) w.push(`lv_obj_set_subject_increment_event_min_value(${objExpr}, ${dsc}, ${e.min});`);
        if (e.max !== undefined) w.push(`lv_obj_set_subject_increment_event_max_value(${objExpr}, ${dsc}, ${e.max});`);
        if (e.rollover !== undefined) w.push(`lv_obj_set_subject_increment_event_rollover(${objExpr}, ${dsc}, ${e.rollover ? 'true' : 'false'});`);
      }
      break;
    }
    case 'screen_load':
    case 'screen_create': {
      // 目标屏可能尚未创建 → 生成惰性跳板(ui_<name>_create 可重入),等价 XML 的按名延迟解析
      const fnName = `screen_evt_${++ctx.trampolineN}_cb`;
      const tw = new CWriter();
      tw.push(`static void ${fnName}(lv_event_t * e)`);
      tw.push('{');
      tw.push(`    LV_UNUSED(e);`);
      tw.push(`    lv_screen_load_anim(ui_${e.screenName}_create(), ${cScreenAnim(e.animType)}, ${e.duration ?? 0}, ${e.delay ?? 0}, false);`);
      tw.push('}');
      ctx.trampolines.push(tw.toString());
      w.push(`lv_obj_add_event_cb(${objExpr}, ${fnName}, ${trig}, NULL);`);
      break;
    }
  }
}

/** 命名节点 create 函数定义(后序:子函数先于调用者) */
function emitNamedCreateFns(node: IRNode, w: CWriter, ctx: ScreenGenCtx): void {
  for (const c of node.children) emitNamedCreateFns(c, w, ctx);
  if (!node.named || node === ctx.screen.root) return;
  const counter = { n: 0 };
  w.push(`static lv_obj_t * create_${node.name}(lv_obj_t * parent)`);
  w.push('{');
  const bw = new CWriter();
  bw.push(`lv_obj_t * obj = ${expandCreate(node, 'parent')};`);
  emitNodeBody(node, 'obj', 'parent', bw, ctx, counter, false);
  bw.push('return obj;');
  for (const line of bw.toString().replace(/\n$/, '').split('\n')) {
    w.push(line === '' ? '' : `    ${line}`);
  }
  w.push('}');
  w.push('');
}

function collectNamed(node: IRNode, out: IRNode[]): void {
  if (node.named) out.push(node);
  for (const c of node.children) collectNamed(c, out);
}

function screenC(
  ir: IRProject,
  screen: IRScreen,
  diags: Diagnostic[],
  callbacks: Set<CName>,
  allowLegacyCPatch: boolean,
): string {
  const ctx: ScreenGenCtx = {
    ir, screen, diags, trampolines: [], trampolineN: 0, callbacks, allowLegacyCPatch,
  };
  const w = new CWriter();

  // 先生成树体(边走边收集 trampolines/callbacks),再拼文件
  const fnsW = new CWriter();
  emitNamedCreateFns(screen.root, fnsW, ctx);

  const rootCounter = { n: 0 };
  const bodyW = new CWriter();
  bodyW.push(`if(ui_${screen.name}.root) return ui_${screen.name}.root;`);
  bodyW.push('');
  bodyW.push('lv_obj_t * root = lv_obj_create(NULL);');
  bodyW.push(`ui_${screen.name}.root = root;`);
  bodyW.push(`lv_obj_set_width(root, ${ir.display.width});`);
  bodyW.push(`lv_obj_set_height(root, ${ir.display.height});`);
  emitNodeBody(screen.root, 'root', '', bodyW, ctx, rootCounter, true);
  bodyW.push('return root;');

  w.push(`/* screens/${screen.name}.c — ${GEN_HEADER.slice(3, -3).trim()} */`);
  w.push('#include "../ui.h"');
  w.push('');
  w.push(`ui_${screen.name}_t ui_${screen.name};`);
  w.push('');
  for (const t of ctx.trampolines) {
    for (const line of t.replace(/\n$/, '').split('\n')) w.push(line);
    w.push('');
  }
  const fnsText = fnsW.toString().replace(/\n+$/, '');
  if (fnsText.trim() !== '') {
    for (const line of fnsText.split('\n')) w.push(line);
    w.push('');
  }
  w.push(`lv_obj_t * ui_${screen.name}_create(void)`);
  w.push('{');
  for (const line of bodyW.toString().replace(/\n$/, '').split('\n')) {
    w.push(line === '' ? '' : `    ${line}`);
  }
  w.push('}');
  w.push('');
  w.push(`void ui_${screen.name}_destroy(void)`);
  w.push('{');
  w.push(`    if(!ui_${screen.name}.root) return;`);
  w.push(`    lv_obj_delete(ui_${screen.name}.root);`);
  w.push(`    lv_memzero(&ui_${screen.name}, sizeof(ui_${screen.name}));`);
  w.push('}');
  return w.toString();
}

/* ------------------------------------------------------------- 共享文件 */

function uiConfH(ir: IRProject): string {
  const w = new CWriter();
  w.push(`/* ui_conf.h — ${GEN_HEADER.slice(3, -3).trim()} */`);
  w.push('#pragma once');
  w.push('');
  w.push('#if defined(LV_LVGL_H_INCLUDE_SIMPLE)');
  w.push('#include "lvgl.h"');
  w.push('#else');
  w.push('#include "lvgl/lvgl.h"');
  w.push('#endif');
  w.push('');
  w.push('/* 回调 weak 兜底(actions_default.c 用)。无 weak 的编译器定义 UI_NO_WEAK,');
  w.push(' * 兜底整体停用,全部回调必须在 actions.c 自行实现(见 INTEGRATION.md)。 */');
  w.push('#if defined(__GNUC__) || defined(__clang__)');
  w.push('#define UI_WEAK __attribute__((weak))');
  w.push('#elif defined(__ICCARM__)');
  w.push('#define UI_WEAK __weak');
  w.push('#else');
  w.push('#define UI_WEAK');
  w.push('#define UI_NO_WEAK 1');
  w.push('#endif');
  if (ir.userIncludes.length > 0) {
    w.push('');
    for (const inc of ir.userIncludes) w.push(`#include "${inc}"`);
  }
  const allConsts = [...ir.consts, ...ir.screens.flatMap((s) => s.consts)];
  if (allConsts.length > 0) {
    w.push('');
    w.push('/* constants */');
    for (const c of allConsts) w.push(constDefine(c));
  }
  return w.toString();
}

function objectsH(ir: IRProject): string {
  const w = new CWriter();
  w.push(`/* objects.h — ${GEN_HEADER.slice(3, -3).trim()} */`);
  w.push('#pragma once');
  w.push('#include "ui_conf.h"');
  for (const screen of ir.screens) {
    const named: IRNode[] = [];
    for (const c of screen.root.children) collectNamed(c, named);
    w.push('');
    w.push('typedef struct {');
    w.push('    lv_obj_t * root;');
    for (const n of named) w.push(`    lv_obj_t * ${n.name};`);
    w.push(`} ui_${screen.name}_t;`);
    w.push('');
    w.push(`extern ui_${screen.name}_t ui_${screen.name};   /* 屏幕未创建时字段为 NULL */`);
  }
  return w.toString();
}

function stylesFiles(ir: IRProject): { h: string; c: string } {
  const all: IRNamedStyle[] = [...ir.styles, ...ir.screens.flatMap((s) => s.styles)];
  const h = new CWriter();
  h.push(`/* styles.h — ${GEN_HEADER.slice(3, -3).trim()} */`);
  h.push('#pragma once');
  h.push('#include "ui_conf.h"');
  h.push('');
  for (const s of all) h.push(`extern lv_style_t style_${s.name};`);
  if (all.length > 0) h.push('');
  h.push('void ui_styles_init(void);');

  const c = new CWriter();
  c.push(`/* styles.c — ${GEN_HEADER.slice(3, -3).trim()} */`);
  c.push('#include "styles.h"');
  c.push('');
  for (const s of all) c.push(`lv_style_t style_${s.name};`);
  if (all.length > 0) c.push('');
  c.push('void ui_styles_init(void)');
  c.push('{');
  c.push('    static bool inited = false;');
  c.push('    if(inited) return;');
  c.push('    inited = true;');
  for (const s of all) {
    c.push('');
    c.push(`    lv_style_init(&style_${s.name});`);
    for (const [k, v] of Object.entries(s.props)) {
      const sp = STYLE_PROPS[k];
      if (!sp) continue;
      c.push(`    lv_style_set_${sp.cSuffix}(&style_${s.name}, ${cValue(v, sp)});`);
    }
  }
  c.push('}');
  return { h: h.toString(), c: c.toString() };
}

function subjectsFiles(ir: IRProject): { h: string; c: string } {
  const h = new CWriter();
  h.push(`/* subjects.h — ${GEN_HEADER.slice(3, -3).trim()} */`);
  h.push('#pragma once');
  h.push('#include "ui_conf.h"');
  h.push('');
  for (const s of ir.subjects) h.push(`extern lv_subject_t subject_${s.name};`);
  if (ir.subjects.length > 0) h.push('');
  h.push('void ui_subjects_init(void);');

  const c = new CWriter();
  c.push(`/* subjects.c — ${GEN_HEADER.slice(3, -3).trim()} */`);
  c.push('#include "subjects.h"');
  c.push('');
  for (const s of ir.subjects) c.push(`lv_subject_t subject_${s.name};`);
  for (const s of ir.subjects) {
    if (s.type === 'string') {
      c.push(`static char subject_${s.name}_buf[${strBufLen(s)}];`);
      c.push(`static char subject_${s.name}_prev_buf[${strBufLen(s)}];`);
    }
  }
  if (ir.subjects.length > 0) c.push('');
  c.push('void ui_subjects_init(void)');
  c.push('{');
  c.push('    static bool inited = false;');
  c.push('    if(inited) return;');
  c.push('    inited = true;');
  if (ir.subjects.length > 0) c.push('');
  for (const s of ir.subjects) {
    switch (s.type) {
      case 'int':
        c.push(`    lv_subject_init_int(&subject_${s.name}, ${s.initial});`);
        if (s.min !== undefined) c.push(`    lv_subject_set_min_value_int(&subject_${s.name}, ${s.min});`);
        if (s.max !== undefined) c.push(`    lv_subject_set_max_value_int(&subject_${s.name}, ${s.max});`);
        break;
      case 'float':
        c.push(`    lv_subject_init_float(&subject_${s.name}, ${s.initial}f);`);
        if (s.min !== undefined) c.push(`    lv_subject_set_min_value_float(&subject_${s.name}, ${s.min}f);`);
        if (s.max !== undefined) c.push(`    lv_subject_set_max_value_float(&subject_${s.name}, ${s.max}f);`);
        break;
      case 'string':
        c.push(`    lv_subject_init_string(&subject_${s.name}, subject_${s.name}_buf, subject_${s.name}_prev_buf, sizeof(subject_${s.name}_buf), ${JSON.stringify(s.initial)});`);
        break;
      case 'color':
        c.push(`    lv_subject_init_color(&subject_${s.name}, lv_color_hex(0x${s.initial.slice(1)}));`);
        break;
    }
  }
  c.push('}');
  return { h: h.toString(), c: c.toString() };
}

function strBufLen(s: SubjectDef & { type: 'string' }): number {
  return Math.max(64, s.initial.length + 1);
}

function imagesH(ir: IRProject): string {
  const w = new CWriter();
  w.push(`/* images.h — ${GEN_HEADER.slice(3, -3).trim()} */`);
  w.push('#pragma once');
  w.push('#include "ui_conf.h"');
  w.push('');
  w.push('/* 图片 C 数组由 asset-pipeline 生成到 images/,符号约定 img_<name> */');
  for (const img of ir.images) w.push(`extern const lv_image_dsc_t img_${img.name};`);
  return w.toString();
}

function fontsH(ir: IRProject): string {
  const w = new CWriter();
  w.push(`/* fonts.h — ${GEN_HEADER.slice(3, -3).trim()} */`);
  w.push('#pragma once');
  w.push('#include "ui_conf.h"');
  w.push('');
  w.push('/* 字体 C 数组由 asset-pipeline(lv_font_conv)生成到 fonts/,符号约定 font_<name> */');
  for (const f of ir.fonts) w.push(`extern const lv_font_t font_${f.name};`);
  return w.toString();
}

function screenH(screen: IRScreen): string {
  const w = new CWriter();
  w.push(`/* screens/${screen.name}.h — ${GEN_HEADER.slice(3, -3).trim()} */`);
  w.push('#pragma once');
  w.push('#include "../ui_conf.h"');
  w.push('');
  w.push(`lv_obj_t * ui_${screen.name}_create(void);   /* 惰性创建,可重入 */`);
  w.push(`void ui_${screen.name}_destroy(void);`);
  return w.toString();
}

function uiH(ir: IRProject): string {
  const w = new CWriter();
  w.push(`/* ui.h — ${GEN_HEADER.slice(3, -3).trim()} */`);
  w.push('#pragma once');
  w.push('');
  w.push('#include "ui_conf.h"');
  w.push('#include "objects.h"');
  w.push('#include "styles.h"');
  w.push('#include "subjects.h"');
  if (ir.images.length > 0) w.push('#include "images.h"');
  if (ir.fonts.length > 0) w.push('#include "fonts.h"');
  w.push('#include "actions.h"');
  for (const s of ir.screens) w.push(`#include "screens/${s.name}.h"`);
  w.push('');
  w.push('void ui_init(void);        /* styles→subjects→入口屏创建并 lv_screen_load */');
  w.push('void ui_deinit(void);');
  return w.toString();
}

function uiC(ir: IRProject): string {
  const w = new CWriter();
  w.push(`/* ui.c — ${GEN_HEADER.slice(3, -3).trim()} */`);
  w.push('#include "ui.h"');
  w.push('');
  w.push('void ui_init(void)');
  w.push('{');
  w.push('    ui_styles_init();');
  w.push('    ui_subjects_init();');
  w.push(`    lv_screen_load(ui_${ir.homeScreenName}_create());`);
  w.push('}');
  w.push('');
  w.push('void ui_deinit(void)');
  w.push('{');
  for (const s of ir.screens) w.push(`    ui_${s.name}_destroy();`);
  w.push('}');
  return w.toString();
}

function actionsFiles(callbacks: CName[]): { h: string; def: string; user: string } {
  const h = new CWriter();
  h.push(`/* actions.h — ${GEN_HEADER.slice(3, -3).trim()};每次导出重生成 */`);
  h.push('#pragma once');
  h.push('#include "ui_conf.h"');
  h.push('');
  for (const cb of callbacks) h.push(`void ${cb}(lv_event_t * e);`);

  const def = new CWriter();
  def.push(`/* actions_default.c — ${GEN_HEADER.slice(3, -3).trim()};weak 空实现兜底 */`);
  def.push('#include "actions.h"');
  def.push('');
  def.push('#ifndef UI_NO_WEAK   /* 无 weak 的编译器:兜底停用,回调须在 actions.c 全部实现 */');
  def.push('');
  for (const cb of callbacks) {
    def.push(`UI_WEAK void ${cb}(lv_event_t * e) { LV_UNUSED(e); }`);
  }
  if (callbacks.length > 0) def.push('');
  def.push('#endif /* !UI_NO_WEAK */');

  const user = new CWriter();
  user.push('/* actions.c — YOURS. Generated once, never overwritten. */');
  user.push('#include "actions.h"');
  for (const cb of callbacks) {
    user.push('');
    user.push(`void ${cb}(lv_event_t * e)`);
    user.push('{');
    user.push('    /* TODO: implement */');
    user.push('    LV_UNUSED(e);');
    user.push('}');
  }
  return { h: h.toString(), def: def.toString(), user: user.toString() };
}

function uiSources(ir: IRProject): string[] {
  return [
    'ui.c', 'styles.c', 'subjects.c', 'actions_default.c', 'actions.c',
    ...ir.screens.map((s) => `screens/${s.name}.c`),
    ...ir.images.map((image) => `images/${image.name}.c`),
    ...ir.fonts.map((font) => `fonts/${font.name}.c`),
  ];
}

function cmakeLists(ir: IRProject): string {
  const w = new CWriter();
  w.push('# CMakeLists.txt — GENERATED by lvgl-web-designer (ESP-IDF component)');
  w.push('idf_component_register(');
  w.push(`    SRCS ${uiSources(ir).map((s) => `"${s}"`).join(' ')}`);
  w.push('    INCLUDE_DIRS "."');
  w.push('    REQUIRES lvgl)');
  return w.toString();
}

function cmakeListsGeneric(ir: IRProject): string {
  const w = new CWriter();
  w.push('# CMakeLists.txt — GENERATED by lvgl-web-designer (generic CMake)');
  w.push('#');
  w.push('# 用法(上层 CMakeLists.txt):');
  w.push('#   add_subdirectory(lvgl)     # 或以其他方式提供 lvgl 库 target');
  w.push('#   add_subdirectory(ui)');
  w.push('#   target_link_libraries(<你的可执行 target> PRIVATE ui)');
  w.push('# 若没有名为 lvgl 的 target,请自行补 lvgl 头文件路径与库:');
  w.push('#   target_include_directories(ui PUBLIC <path/to/lvgl 上级目录>)');
  w.push('#   target_link_libraries(ui PUBLIC <你的 lvgl 库>)');
  w.push('add_library(ui STATIC');
  for (const s of uiSources(ir)) w.push(`    ${s}`);
  w.push(')');
  w.push('target_include_directories(ui PUBLIC ${CMAKE_CURRENT_LIST_DIR})');
  w.push('if(TARGET lvgl)');
  w.push('    target_link_libraries(ui PUBLIC lvgl)');
  w.push('endif()');
  return w.toString();
}

const COLOR_FORMAT_DEPTH: Partial<Record<ColorFormat, 16 | 24 | 32>> = {
  RGB565: 16,
  RGB565_SWAPPED: 16,
  RGB888: 24,
  XRGB8888: 32,
  ARGB8888: 32,
};

function resolveTargetColorFormat(
  ir: IRProject,
  lvglVersion: CEmitterVersion,
  requested: ColorFormat | undefined,
  diagnostics: Diagnostic[],
): ColorFormat | null {
  if (lvglVersion === '9.4.0') return null;
  if (requested === undefined) {
    if (ir.display.colorDepth === 16) {
      diagnostics.push({
        severity: 'error',
        code: 'E_COLOR_FORMAT_CONFIRM_REQUIRED',
        message: 'v1 colorDepth=16 无法区分 RGB565 与 RGB565_SWAPPED，发布前必须由 DisplayProfile 明确确认',
      });
      return null;
    }
    return ir.display.colorDepth === 24 ? 'RGB888' : 'XRGB8888';
  }
  if (COLOR_FORMAT_DEPTH[requested] !== ir.display.colorDepth) {
    diagnostics.push({
      severity: 'error',
      code: 'E_COLOR_FORMAT_DEPTH_MISMATCH',
      message: `DisplayProfile.colorFormat=${requested} 与 v1 colorDepth=${ir.display.colorDepth} 不兼容`,
    });
    return null;
  }
  return requested;
}

function buildManifest(
  ir: IRProject,
  target: CTarget,
  lvglVersion: CEmitterVersion,
  unimplementedActions: CName[],
  colorFormat: ColorFormat | null,
  options?: EmitC94Options,
): string {
  const req = collectRequirements(ir);
  const manifest = {
    formatVersion: 1,
    generator: '@lvd/codegen',
    lvglVersion,
    target,
    display: {
      width: ir.display.width,
      height: ir.display.height,
      colorFormat,
    },
    profiles: options?.buildTarget === undefined ? null : {
      buildTarget: {
        id: options.buildTarget.id,
        revision: options.buildTarget.revision,
      },
      uiProjectRef: options.buildTarget.uiProjectRef,
      controllerProfileRef: options.buildTarget.controllerProfileRef,
      displayProfileRef: options.displayProfileRef ?? null,
      themeRef: options.buildTarget.themeRef,
    },
    lvConf: {
      widgets: req.lvUse,
      montserrat: req.montserrat,
      flex: req.needsFlex,
      grid: req.needsGrid,
      observer: req.needsObserver,
    },
    assets: {
      fonts: ir.fonts.map((f) => ({
        name: f.name, sha256: f.file.sha256, byteSize: f.file.byteSize,
      })),
      images: ir.images.map((image) => ({
        name: image.name, sha256: image.file.sha256, byteSize: image.file.byteSize,
        colorFormat: image.conv.colorFormat,
      })),
    },
    unimplementedActions,
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/* ------------------------------------------------------------------ 入口 */

/**
 * 9.4/9.5 共享的 C lowering。Registry 中用到的 197 个 C 符号已通过
 * registry-lvgl95-parity.test.ts 与 9.5.0 真实符号表对账。
 */
export function emitCForVersionFromIr(
  ir: IRProject,
  diagnostics: Diagnostic[],
  lvglVersion: CEmitterVersion,
  options?: EmitC94Options,
): CEmitResult {
  const target: CTarget = options?.target ?? 'esp-idf';
  const diags = [...diagnostics];
  const colorFormat = resolveTargetColorFormat(ir, lvglVersion, options?.colorFormat, diags);
  if (options?.buildTarget !== undefined && options.buildTarget.lvglVersion !== lvglVersion) {
    diags.push({
      severity: 'error',
      code: 'E_BUILD_TARGET_VERSION_MISMATCH',
      message: `BuildTarget.lvglVersion=${options.buildTarget.lvglVersion} 与 emitter ${lvglVersion} 不一致`,
    });
  }
  if (lvglVersion === '9.5.0' && options?.buildTarget !== undefined
    && options.displayProfileRef === undefined) {
    diags.push({
      severity: 'error',
      code: 'E_DISPLAY_PROFILE_REF_REQUIRED',
      message: 'BuildTarget 发布 manifest 必须锁定带 revision 的 DisplayProfile 引用',
    });
  }
  const callbacks = new Set<CName>();

  const screenFiles: GeneratedFile[] = [];
  for (const screen of ir.screens) {
    screenFiles.push({ path: `screens/${screen.name}.h`, content: screenH(screen) });
    screenFiles.push({
      path: `screens/${screen.name}.c`,
      content: screenC(ir, screen, diags, callbacks, lvglVersion === '9.4.0'),
    });
  }

  const cbList = [...callbacks].sort();
  const actions = actionsFiles(cbList);
  const styles = stylesFiles(ir);
  const subjects = subjectsFiles(ir);

  const buildFiles: GeneratedFile[] =
    target === 'esp-idf' ? [{ path: 'CMakeLists.txt', content: cmakeLists(ir) }]
    : target === 'cmake' ? [{ path: 'CMakeLists.txt', content: cmakeListsGeneric(ir) }]
    : [];

  const files: GeneratedFile[] = [
    ...buildFiles,
    // 9.4 入口保持历史文件集不变;9.5 发布链强制带可追溯 manifest。
    ...(lvglVersion === '9.5.0'
      ? [{
          path: 'build-manifest.json',
          content: buildManifest(ir, target, lvglVersion, cbList, colorFormat, options),
        }]
      : []),
    { path: 'REQUIREMENTS.txt', content: requirementsTxt(ir, lvglVersion) },
    { path: 'INTEGRATION.md', content: integrationMd(ir, lvglVersion) },
    { path: 'ui_conf.h', content: uiConfH(ir) },
    { path: 'objects.h', content: objectsH(ir) },
    { path: 'styles.h', content: styles.h },
    { path: 'styles.c', content: styles.c },
    { path: 'subjects.h', content: subjects.h },
    { path: 'subjects.c', content: subjects.c },
    ...(ir.images.length > 0 ? [{ path: 'images.h', content: imagesH(ir) }] : []),
    ...(ir.fonts.length > 0 ? [{ path: 'fonts.h', content: fontsH(ir) }] : []),
    { path: 'ui.h', content: uiH(ir) },
    { path: 'ui.c', content: uiC(ir) },
    ...screenFiles,
    { path: 'actions.h', content: actions.h },
    { path: 'actions_default.c', content: actions.def },
    { path: 'actions.c', content: actions.user, overwrite: false },
  ];

  return { files, diagnostics: diags };
}

export function emitC94FromIr(
  ir: IRProject,
  diagnostics: Diagnostic[],
  options?: EmitC94Options,
): CEmitResult {
  return emitCForVersionFromIr(ir, diagnostics, '9.4.0', options);
}

/** 契约入口:emitC94(project, options?);options 缺省 target='esp-idf'(向后兼容) */
export function emitC94(project: LvProject, options?: EmitC94Options): CEmitResult {
  const { ir, diagnostics } = normalizeProject(project);
  return emitC94FromIr(ir, diagnostics, options);
}
