/**
 * REQUIREMENTS.txt / INTEGRATION.md 生成(design/03 §3 多目标导出)。
 * - LV_USE_*:从 registry lvUseGuard 按实际用到的 widget 收集,
 *   加内部实现依赖闭包(WIDGET_DEPS,逐项核对 vendor/lvgl 9.4 源码)
 * - LV_FONT_MONTSERRAT_N:样式(命名/内联)text_font 用到的内置字体
 * - LV_USE_FLEX / LV_USE_GRID / LV_USE_OBSERVER 按特征检测
 */
import { M1_TEXT_FONTS, REGISTRY, type PropValue } from '@lvd/schema';
import type { IRNode, IRProject } from '@lvd/compiler-core';

/**
 * widget 内部实现依赖(值 = registry type)。事实来源 vendor/lvgl 9.4:
 * - animimage→image(lv_animimage.c #error)/ keyboard→buttonmatrix+textarea(lv_keyboard.c #error)
 * - msgbox→label+image、textarea→label、dropdown→label、calendar→buttonmatrix+button+label、
 *   list→button+label+image、menu/win→button+image+label、tabview→button+label
 *   (各 lv_*.c 内 lv_<dep>_create / base_class 实测)
 * - qrcode/lottie base_class = lv_canvas_class → canvas;spinbox base_class = textarea
 */
const WIDGET_DEPS: Record<string, readonly string[]> = {
  animimage: ['image'],
  calendar: ['buttonmatrix', 'button', 'label'],
  dropdown: ['label'],
  keyboard: ['buttonmatrix', 'textarea'],
  list: ['button', 'label', 'image'],
  lottie: ['canvas'],
  menu: ['button', 'image', 'label'],
  msgbox: ['label', 'image'],
  qrcode: ['canvas'],
  spinbox: ['textarea'],
  tabview: ['button', 'label'],
  textarea: ['label'],
  win: ['button', 'image', 'label'],
};

export interface Requirements {
  /** LV_USE_<WIDGET> 宏名,已含依赖闭包,字典序 */
  lvUse: string[];
  /** 用到的内置 montserrat 字号,升序 */
  montserrat: number[];
  needsFlex: boolean;
  needsGrid: boolean;
  needsObserver: boolean;
  usesLottie: boolean;
  colorDepth: number;
}

/** 生成物钉死到精确 LVGL 版本，不使用 ^/~ 漂移范围。 */
export type LvglCVersion = '9.4.0' | '9.5.0';

function walk(node: IRNode, fn: (n: IRNode) => void): void {
  fn(node);
  for (const c of node.children) walk(c, fn);
}

/** 收集一份 style props(命名样式/内联组通用)里的布局与字体特征 */
function scanStyleProps(
  props: Record<string, PropValue>,
  req: { flex: boolean; grid: boolean; fonts: Set<number> },
): { flex: boolean; grid: boolean; fonts: Set<number> } {
  for (const [k, v] of Object.entries(props)) {
    if (k.startsWith('flex_') || (k === 'layout' && v === 'flex')) req.flex = true;
    if (k.startsWith('grid_') || (k === 'layout' && v === 'grid')) req.grid = true;
    if (k === 'text_font' && typeof v === 'string' && M1_TEXT_FONTS.includes(v)) {
      req.fonts.add(Number(v.replace('montserrat_', '')));
    }
  }
  return req;
}

export function collectRequirements(ir: IRProject): Requirements {
  const types = new Set<string>();
  const feat = { flex: false, grid: false, fonts: new Set<number>() };

  for (const s of [...ir.styles, ...ir.screens.flatMap((sc) => sc.styles)]) {
    scanStyleProps(s.props, feat);
  }

  for (const screen of ir.screens) {
    walk(screen.root, (n) => {
      // ChildSpec 类型(chart-series 等)不在 REGISTRY,守卫由父 widget 承担
      if (REGISTRY.has(n.type)) types.add(n.type);
      scanStyleProps(n.props, feat);           // OBJ_BASE 的 flex_flow/flex_grow 走 props
      for (const g of n.inlineStyles) scanStyleProps(g.props, feat);
    });
  }

  // 依赖闭包(spinbox→textarea→label 两跳)
  let grew = true;
  while (grew) {
    grew = false;
    for (const t of [...types]) {
      for (const dep of WIDGET_DEPS[t] ?? []) {
        if (!types.has(dep)) { types.add(dep); grew = true; }
      }
    }
  }

  const lvUse = [...types]
    .map((t) => REGISTRY.get(t)!.lvUseGuard)
    .filter((g) => g !== 'LV_USE_OBJ')          // 基类 obj 无 lv_conf 开关
    .sort();

  return {
    lvUse: [...new Set(lvUse)],
    montserrat: [...feat.fonts].sort((a, b) => a - b),
    needsFlex: feat.flex,
    needsGrid: feat.grid,
    needsObserver: ir.subjects.length > 0,
    usesLottie: types.has('lottie'),
    colorDepth: ir.display.colorDepth,
  };
}

/* -------------------------------------------------------- REQUIREMENTS.txt */

export function requirementsTxt(ir: IRProject, lvglVersion: LvglCVersion = '9.4.0'): string {
  const r = collectRequirements(ir);
  const displayVersion = lvglVersion === '9.4.0' ? '9.4' : lvglVersion;
  const L: string[] = [];
  L.push('# REQUIREMENTS.txt — GENERATED by lvgl-web-designer');
  L.push(`# LVGL ${displayVersion} 生成代码。逐项对照你的 lv_conf.h,确保下列宏取值一致。`);
  L.push('');
  L.push('# ---- widgets(含内部实现依赖,如 spinbox→textarea→label) ----');
  for (const g of r.lvUse) L.push(`${g} 1`);
  if (r.usesLottie) {
    L.push('LV_USE_THORVG_INTERNAL 1    # lottie 渲染引擎(已集成外部 thorvg 则改 LV_USE_THORVG_EXTERNAL 1)');
  }
  if (r.needsFlex || r.needsGrid || r.needsObserver) {
    L.push('');
    L.push('# ---- 布局 / 数据绑定 ----');
    if (r.needsFlex) L.push('LV_USE_FLEX 1');
    if (r.needsGrid) L.push('LV_USE_GRID 1');
    if (r.needsObserver) L.push('LV_USE_OBSERVER 1    # subject 数据绑定');
  }
  if (r.montserrat.length > 0) {
    L.push('');
    L.push('# ---- 内置字体(样式 text_font 用到) ----');
    for (const nn of r.montserrat) L.push(`LV_FONT_MONTSERRAT_${nn} 1`);
  }
  if (ir.fonts.length > 0) {
    L.push('');
    L.push('# ---- 自定义字体(lv_font_conv 产物,编入工程即可,无 lv_conf 开关) ----');
    for (const f of ir.fonts) L.push(`# font_${f.name}(fonts.h 已 extern 声明)`);
  }
  L.push('');
  L.push('# ---- 可选 ----');
  L.push('LV_USE_OBJ_NAME 1    # 对象命名;生成代码已用 #if 守卫,置 0 同样可编译,仅失去按名查找');
  L.push('');
  L.push('# ---- 建议(与设计器工程设置一致) ----');
  L.push(`LV_COLOR_DEPTH ${r.colorDepth}`);
  return `${L.join('\n')}\n`;
}

/* --------------------------------------------------------- INTEGRATION.md */

export function integrationMd(ir: IRProject, lvglVersion: LvglCVersion = '9.4.0'): string {
  const screenSrcs = ir.screens.map((s) => `screens/${s.name}.c`).join(' ');
  const displayVersion = lvglVersion === '9.4.0' ? '9.4' : lvglVersion;
  const platformIoVersion = lvglVersion === '9.4.0' ? '^9.4.0' : lvglVersion;
  return `# 集成指南 — GENERATED by lvgl-web-designer

本目录是自包含的 LVGL ${displayVersion} UI 源码。任何工程接入都是三步:

1. 把本目录整体拷入工程(下文以 \`ui/\` 指代);
2. 按 \`REQUIREMENTS.txt\` 逐项核对 \`lv_conf.h\`;
3. 在 \`lv_init()\` 与显示/输入驱动就绪之后调用一次 \`ui_init();\`,主循环照常跑 \`lv_timer_handler()\`。

事件回调:\`actions.h\` 里声明的回调在 \`actions.c\` 生成了空实现骨架(该文件**不会被再次导出覆盖**,业务逻辑写这里);\`actions_default.c\` 提供 weak 空实现兜底,没实现的回调也能链接。若编译器不支持 weak(此时 \`ui_conf.h\` 会定义 \`UI_NO_WEAK\`),\`actions_default.c\` 整体失效,**必须**在 \`actions.c\` 实现全部回调。

## STM32CubeIDE

1. 把 \`ui/\` 拷入工程(如 \`Core/ui/\`),或拖入 Project Explorer 并勾选 copy;
2. Project → Properties → C/C++ General → Paths and Symbols → Includes,加入 \`ui/\` 目录(GNU C);
3. \`lv_conf.h\` 按 \`REQUIREMENTS.txt\` 勾选;
4. \`main.c\`:\`lv_init()\` + 显示驱动注册之后调用 \`ui_init();\`,\`while(1)\` 里调 \`lv_timer_handler();\`(配合 \`lv_tick_inc\` 常规接法)。

## Makefile

\`\`\`make
UI_DIR := ui
SRCS   += $(wildcard $(UI_DIR)/*.c) $(wildcard $(UI_DIR)/screens/*.c)
CFLAGS += -I$(UI_DIR)
\`\`\`

(本工程 screens:${screenSrcs};actions.c / actions_default.c 都要参与编译。)

## PlatformIO

把 \`ui/\` 放进 \`src/\`(或作为 \`lib/ui\` 私有库),\`platformio.ini\`:

\`\`\`ini
build_flags = -Isrc/ui
lib_deps = lvgl/lvgl@${platformIoVersion}
\`\`\`

\`lv_conf.h\` 的放置与 \`LV_CONF_PATH\` 按 PlatformIO + LVGL 常规;其余同上。

## ESP-IDF

选 target=esp-idf 导出的 \`CMakeLists.txt\` 即组件清单:目录放到 \`components/ui/\` 即插即用(\`REQUIRES lvgl\`)。
`;
}
