"""Validation boundary for LVGL project documents written to platform storage.

Schema v2 structure is validated from the JSON Schema generated by
``@lvd/schema``.  Security and cross-reference checks remain server-side so a
client cannot bypass them by calling the API directly.  Schema v1 is accepted
only as a migration compatibility format until Designer persistence switches
fully to v2.
"""

from __future__ import annotations

import json
import os
import re
from functools import lru_cache
from pathlib import Path
from typing import Any, Iterable

from jsonschema import Draft202012Validator

WORKSPACE_ROOT = Path(__file__).resolve().parents[4]
SCHEMA_DIR = WORKSPACE_ROOT / "packages" / "schema" / "schema"

MAX_DOCUMENT_BYTES = int(os.environ.get("LVGL_PROJECT_MAX_BYTES", 10 * 1024 * 1024))
MAX_NODES = int(os.environ.get("LVGL_PROJECT_MAX_NODES", 10_000))
MAX_TREE_DEPTH = int(os.environ.get("LVGL_PROJECT_MAX_DEPTH", 64))
MAX_ISSUES = 100

C_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")
C_KEYWORDS = {
    "auto", "break", "case", "char", "const", "continue", "default", "do",
    "double", "else", "enum", "extern", "float", "for", "goto", "if",
    "inline", "int", "long", "register", "restrict", "return", "short",
    "signed", "sizeof", "static", "struct", "switch", "typedef", "union",
    "unsigned", "void", "volatile", "while",
}
BUILTIN_ACTIONS = {
    "screen.open", "screen.create", "screen.back",
    "subject.set", "subject.toggle", "subject.increment",
}
ACTION_REQUIRED_ARGS = {
    "screen.open": {"screen"},
    "screen.create": {"screen"},
    "screen.back": set(),
    "subject.set": {"subject", "value"},
    "subject.toggle": {"subject"},
    "subject.increment": {"subject"},
}
FORBIDDEN_KEYS = {"cPatch", "trustedExtension", "trustedExtensions"}
CATALOG_SCHEMAS = {
    "display-profile": "display-profile.schema.json",
    "controller-profile": "controller-profile.schema.json",
    "input-profile": "input-profile.schema.json",
    "firmware-profile": "firmware-profile.schema.json",
    "lvgl-theme": "theme.schema.json",
    "lvgl-build-target": "build-target.schema.json",
}
CATALOG_ID_PREFIXES = {
    "display-profile": "display",
    "controller-profile": "controller",
    "input-profile": "input",
    "firmware-profile": "firmware",
    "lvgl-theme": "theme",
    "lvgl-build-target": "target",
}


class ProjectDocumentValidationError(ValueError):
    """A project document failed structural, semantic, or trust validation."""

    def __init__(self, issues: list[dict[str, str]]):
        self.issues = issues[:MAX_ISSUES]
        message = self.issues[0]["message"] if self.issues else "工程文档校验失败"
        super().__init__(message)


def _issue(issues: list[dict[str, str]], code: str, path: str, message: str) -> None:
    if len(issues) < MAX_ISSUES:
        issues.append({"code": code, "path": path, "message": message})


def _path(parts: Iterable[Any]) -> str:
    out = "$"
    for part in parts:
        out += f"[{part}]" if isinstance(part, int) else f".{part}"
    return out


@lru_cache(maxsize=8)
def _schema_validator(name: str) -> Draft202012Validator:
    path = SCHEMA_DIR / name
    try:
        schema = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"无法加载 LVGL Schema: {path}: {exc}") from exc
    Draft202012Validator.check_schema(schema)
    return Draft202012Validator(schema)


def _scan_trust(value: Any, issues: list[dict[str, str]]) -> None:
    """Iterative scan avoids recursion failures on deliberately deep input."""

    stack: list[tuple[Any, tuple[Any, ...], int]] = [(value, (), 0)]
    while stack and len(issues) < MAX_ISSUES:
        current, parts, depth = stack.pop()
        if depth > MAX_TREE_DEPTH * 3:
            _issue(issues, "document-depth", _path(parts), "JSON 嵌套层级超过安全限制")
            continue
        if isinstance(current, dict):
            if current.get("kind") == "trusted-extension":
                _issue(issues, "trusted-extension-forbidden", _path(parts),
                       "普通工程写入接口禁止携带 trusted extension")
            for key, child in current.items():
                child_parts = (*parts, key)
                if key in FORBIDDEN_KEYS:
                    _issue(issues, "untrusted-code-forbidden", _path(child_parts),
                           f"普通工程禁止字段 {key}；可信扩展必须走独立审核和发布流程")
                stack.append((child, child_parts, depth + 1))
        elif isinstance(current, list):
            for index, child in enumerate(current):
                stack.append((child, (*parts, index), depth + 1))


def _check_c_name(value: Any, issues: list[dict[str, str]], path: str) -> None:
    if not isinstance(value, str) or not C_NAME_RE.fullmatch(value):
        _issue(issues, "bad-code-name", path, "C 标识符必须匹配 /^[a-z][a-z0-9_]*$/")
    elif len(value) > 63:
        _issue(issues, "bad-code-name", path, "C 标识符长度不能超过 63")
    elif value in C_KEYWORDS or value.startswith(("lv_", "ui_")):
        _issue(issues, "reserved-code-name", path, f"C 标识符 {value!r} 使用了关键字或保留前缀")


def _validate_v1(doc: dict[str, Any], issues: list[dict[str, str]]) -> None:
    """Validate the legacy editable subset without treating it as the new truth model."""

    required = {
        "meta": dict, "display": dict, "screens": list, "components": list,
        "styles": list, "consts": list, "subjects": list, "assets": dict,
        "translations": (dict, type(None)), "codegen": dict,
    }
    for key, expected in required.items():
        if not isinstance(doc.get(key), expected):
            _issue(issues, "legacy-schema", f"$.{key}", f"v1 字段 {key} 缺失或类型错误")
    if issues:
        return

    meta = doc["meta"]
    display = doc["display"]
    if not isinstance(meta.get("name"), str) or meta.get("lvglVersion") != "9.4":
        _issue(issues, "legacy-schema", "$.meta", "v1 meta.name/lvglVersion 不合法")
    if display.get("shape") not in {"rect", "round"} or display.get("colorDepth") not in {16, 24, 32}:
        _issue(issues, "legacy-schema", "$.display", "v1 display.shape/colorDepth 不合法")
    if not isinstance(display.get("width"), int) or not isinstance(display.get("height"), int):
        _issue(issues, "legacy-schema", "$.display", "v1 display.width/height 必须为整数")
    if not doc["screens"]:
        _issue(issues, "legacy-schema", "$.screens", "工程至少需要一个 screen")

    seen_ids: set[str] = set()
    node_count = 0

    def visit(node: Any, path: str, depth: int) -> None:
        nonlocal node_count
        if not isinstance(node, dict):
            _issue(issues, "legacy-schema", path, "widget 必须是对象")
            return
        node_count += 1
        if node_count > MAX_NODES:
            _issue(issues, "node-limit", path, f"节点数量超过限制 {MAX_NODES}")
            return
        if depth > MAX_TREE_DEPTH:
            _issue(issues, "depth-limit", path, f"节点树深度超过限制 {MAX_TREE_DEPTH}")
            return
        node_id = node.get("id")
        if not isinstance(node_id, str) or not node_id:
            _issue(issues, "legacy-schema", f"{path}.id", "widget id 必须是非空字符串")
        elif node_id in seen_ids:
            _issue(issues, "duplicate-id", f"{path}.id", f"重复节点 id {node_id!r}")
        else:
            seen_ids.add(node_id)
        if "name" in node:
            _check_c_name(node["name"], issues, f"{path}.name")
        children = node.get("children")
        if not isinstance(children, list):
            _issue(issues, "legacy-schema", f"{path}.children", "widget children 必须是数组")
            return
        for index, child in enumerate(children):
            visit(child, f"{path}.children[{index}]", depth + 1)

    for index, screen in enumerate(doc["screens"]):
        path = f"$.screens[{index}]"
        if not isinstance(screen, dict):
            _issue(issues, "legacy-schema", path, "screen 必须是对象")
            continue
        _check_c_name(screen.get("name"), issues, f"{path}.name")
        root = screen.get("root")
        if not isinstance(root, dict) or root.get("type") != "obj":
            _issue(issues, "bad-root-type", f"{path}.root", "screen 根节点 type 必须是 obj")
        visit(root, f"{path}.root", 1)


def _validate_v2_semantics(
    doc: dict[str, Any],
    issues: list[dict[str, str]],
    allowed_actions: set[str] | None = None,
) -> None:
    allowed_actions = BUILTIN_ACTIONS if allowed_actions is None else allowed_actions
    screen_ids = {screen["id"] for screen in doc["screens"]}
    subject_ids = {subject["id"] for subject in doc["subjects"]}
    style_ids: set[str] = set()
    for style in doc["styles"]:
        style_ids.add(style["id"])
    for owner in [*doc["screens"], *doc["components"]]:
        for style in owner["styles"]:
            style_ids.add(style["id"])

    for label, values, total in (
        ("screen", screen_ids, len(doc["screens"])),
        ("subject", subject_ids, len(doc["subjects"])),
    ):
        if len(values) != total:
            _issue(issues, f"duplicate-{label}-id", f"$.{label}s", f"{label} id 必须全局唯一")

    all_style_count = len(doc["styles"]) + sum(
        len(owner["styles"]) for owner in [*doc["screens"], *doc["components"]]
    )
    if len(style_ids) != all_style_count:
        _issue(issues, "duplicate-style-id", "$.styles", "命名样式 id 必须全局唯一")

    theme_ids = {theme["id"] for theme in doc["themes"]}
    if len(theme_ids) != len(doc["themes"]):
        _issue(issues, "duplicate-theme-id", "$.themes", "theme id 必须唯一")
    theme_parent: dict[str, str] = {}
    for index, theme in enumerate(doc["themes"]):
        parent = theme.get("extends")
        if parent is not None and parent not in theme_ids:
            _issue(issues, "theme-parent-missing", f"$.themes[{index}].extends",
                   f"继承了不存在的 theme {parent!r}")
        elif parent is not None:
            theme_parent[theme["id"]] = parent
        token_ids = [token["id"] for token in theme["tokens"]]
        if len(set(token_ids)) != len(token_ids):
            _issue(issues, "duplicate-token", f"$.themes[{index}].tokens",
                   f"theme {theme['id']!r} 内 token id 必须唯一")
    for start in theme_parent:
        seen: set[str] = set()
        current = start
        while current in theme_parent:
            if current in seen:
                _issue(issues, "theme-cycle", "$.themes", f"theme {start!r} 的继承链成环")
                break
            seen.add(current)
            current = theme_parent[current]

    homes = sum(1 for screen in doc["screens"] if screen.get("isHome") is True)
    if homes > 1:
        _issue(issues, "multiple-home", "$.screens", "只能有一个 screen 标记 isHome")

    code_names: set[str] = set()
    node_ids: set[str] = set()
    node_count = 0

    def add_code_name(value: Any, path: str) -> None:
        if value is None:
            return
        _check_c_name(value, issues, path)
        if isinstance(value, str):
            if value in code_names:
                _issue(issues, "duplicate-code-name", path, f"重复 C 标识符 {value!r}")
            code_names.add(value)

    for index, subject in enumerate(doc["subjects"]):
        add_code_name(subject["codeName"], f"$.subjects[{index}].codeName")

    def visit(node: dict[str, Any], path: str, depth: int) -> None:
        nonlocal node_count
        node_count += 1
        if node_count > MAX_NODES:
            _issue(issues, "node-limit", path, f"节点数量超过限制 {MAX_NODES}")
            return
        if depth > MAX_TREE_DEPTH:
            _issue(issues, "depth-limit", path, f"节点树深度超过限制 {MAX_TREE_DEPTH}")
            return

        node_id = node["id"]
        if node_id in node_ids:
            _issue(issues, "duplicate-id", f"{path}.id", f"重复节点 id {node_id!r}")
        node_ids.add(node_id)
        add_code_name(node.get("codeName"), f"{path}.codeName")

        for index, ref in enumerate(node["styleRefs"]):
            if ref["styleId"] not in style_ids:
                _issue(issues, "style-not-found", f"{path}.styleRefs[{index}].styleId",
                       f"引用了不存在的样式 {ref['styleId']!r}")
        for index, binding in enumerate(node["bindings"]):
            if binding["subject"] not in subject_ids:
                _issue(issues, "subject-not-found", f"{path}.bindings[{index}].subject",
                       f"引用了不存在的 subject {binding['subject']!r}")
            if binding["kind"] == "style" and binding["styleId"] not in style_ids:
                _issue(issues, "style-not-found", f"{path}.bindings[{index}].styleId",
                       f"引用了不存在的样式 {binding['styleId']!r}")
        for index, event in enumerate(node["events"]):
            event_path = f"{path}.events[{index}]"
            action = event["action"]
            if action not in allowed_actions:
                _issue(issues, "unknown-action", f"{event_path}.action",
                       f"Action {action!r} 未登记在服务端 Action Registry")
            args = event.get("args", {})
            for required in ACTION_REQUIRED_ARGS.get(action, set()):
                if required not in args:
                    _issue(issues, "missing-action-arg", f"{event_path}.args",
                           f"Action {action!r} 缺少必填参数 {required!r}")
            screen = args.get("screen")
            subject = args.get("subject")
            if screen is not None and screen not in screen_ids:
                _issue(issues, "screen-not-found", f"{event_path}.args.screen",
                       f"引用了不存在的 screen {screen!r}")
            if subject is not None and subject not in subject_ids:
                _issue(issues, "subject-not-found", f"{event_path}.args.subject",
                       f"引用了不存在的 subject {subject!r}")
        for index, child in enumerate(node["children"]):
            visit(child, f"{path}.children[{index}]", depth + 1)

    for index, screen in enumerate(doc["screens"]):
        path = f"$.screens[{index}]"
        add_code_name(screen["codeName"], f"{path}.codeName")
        if screen["root"]["type"] != "obj":
            _issue(issues, "bad-root-type", f"{path}.root.type", "screen 根节点 type 必须是 obj")
        visit(screen["root"], f"{path}.root", 1)
    for index, component in enumerate(doc["components"]):
        path = f"$.components[{index}]"
        add_code_name(component["codeName"], f"{path}.codeName")
        visit(component["root"], f"{path}.root", 1)

    for group in (doc["assets"]["fonts"], doc["assets"]["images"], doc["assets"]["icons"]):
        for asset in group:
            digest = asset["file"]["sha256"]
            if not re.fullmatch(r"[0-9a-f]{64}", digest):
                _issue(issues, "bad-asset-sha256", "$.assets", "素材 sha256 必须是 64 位小写十六进制")


def _append_schema_issues(
    name: str,
    value: Any,
    issues: list[dict[str, str]],
    prefix: tuple[Any, ...] = (),
) -> bool:
    errors = sorted(_schema_validator(name).iter_errors(value), key=lambda item: list(item.absolute_path))
    for error in errors:
        _issue(issues, "schema", _path((*prefix, *error.absolute_path)), error.message)
    return not errors


def _validate_snapshot(doc: dict[str, Any], issues: list[dict[str, str]]) -> None:
    required = {
        "kind", "snapshotVersion", "uiProject", "displayProfile",
        "controllerProfile", "buildTarget", "actionRegistry", "migrationNotes",
        "colorFormatConfirmed",
    }
    extra = set(doc) - required
    missing = required - set(doc)
    if extra:
        _issue(issues, "snapshot-schema", "$", f"快照包含未知字段: {sorted(extra)}")
    if missing:
        _issue(issues, "snapshot-schema", "$", f"快照缺少字段: {sorted(missing)}")
        return
    if doc.get("snapshotVersion") != 1:
        _issue(issues, "snapshot-version", "$.snapshotVersion", "仅支持 snapshotVersion=1")
        return
    if not isinstance(doc["colorFormatConfirmed"], bool):
        _issue(issues, "snapshot-schema", "$.colorFormatConfirmed", "色彩格式确认状态必须是布尔值")
    if not isinstance(doc["migrationNotes"], list):
        _issue(issues, "snapshot-schema", "$.migrationNotes", "迁移诊断必须是数组")

    actions = doc["actionRegistry"]
    allowed_actions = set(BUILTIN_ACTIONS)
    if not isinstance(actions, dict):
        _issue(issues, "action-registry-schema", "$.actionRegistry", "Action Registry 必须是对象")
    else:
        for action_id, spec in actions.items():
            path = f"$.actionRegistry.{action_id}"
            if not isinstance(action_id, str) or not re.fullmatch(r"[a-z][a-z0-9_.-]*", action_id):
                _issue(issues, "bad-action-id", path, f"Action id {action_id!r} 不合法")
                continue
            if not isinstance(spec, dict) or spec.get("id") != action_id or not isinstance(spec.get("params"), list):
                _issue(issues, "action-registry-schema", path, "Action 契约的 id/params 不合法")
                continue
            allowed_actions.add(action_id)

    ui = doc["uiProject"]
    if _append_schema_issues("ui.schema.json", ui, issues, ("uiProject",)):
        before = len(issues)
        _validate_v2_semantics(ui, issues, allowed_actions)
        for issue in issues[before:]:
            issue["path"] = f"$.uiProject{issue['path'][1:]}"

    display = doc["displayProfile"]
    _append_schema_issues("display-profile.schema.json", display, issues, ("displayProfile",))
    controller = doc["controllerProfile"]
    if controller is not None:
        _append_schema_issues("controller-profile.schema.json", controller, issues, ("controllerProfile",))

    target = doc["buildTarget"]
    if not isinstance(target, dict):
        _issue(issues, "build-target-schema", "$.buildTarget", "BuildTarget 必须是对象")
        return
    if controller is not None:
        _append_schema_issues("build-target.schema.json", target, issues, ("buildTarget",))
    else:
        for key in ("schemaVersion", "kind", "id", "revision", "uiProjectRef", "themeRef", "lvglVersion"):
            if key not in target:
                _issue(issues, "build-target-schema", f"$.buildTarget.{key}", "BuildTarget 草稿缺少字段")

    if isinstance(ui, dict) and isinstance(display, dict):
        expected_display = f"{display.get('id')}@{display.get('revision')}"
        if ui.get("designDisplayRef") != expected_display:
            _issue(issues, "display-ref-mismatch", "$.uiProject.designDisplayRef",
                   "UiProject 与 DisplayProfile revision 不一致")
        meta = ui.get("meta")
        if isinstance(meta, dict):
            expected_ui = f"{meta.get('id')}@{meta.get('revision')}"
            if target.get("uiProjectRef") != expected_ui:
                _issue(issues, "ui-ref-mismatch", "$.buildTarget.uiProjectRef",
                       "BuildTarget 与 UiProject revision 不一致")
            theme_ref = str(target.get("themeRef", ""))
            embedded_theme = theme_ref.startswith(f"{expected_ui}#theme:")
            standalone_theme = re.fullmatch(r"theme:[a-z0-9][a-z0-9._-]*@[1-9]\d*", theme_ref) is not None
            if not embedded_theme and not standalone_theme:
                _issue(issues, "theme-ref-mismatch", "$.buildTarget.themeRef",
                       "BuildTarget.themeRef 必须属于当前 UiProject revision 或引用独立 Theme revision")
    if isinstance(controller, dict) and isinstance(display, dict):
        expected_display = f"{display.get('id')}@{display.get('revision')}"
        if controller.get("displayRef") != expected_display:
            _issue(issues, "controller-display-ref-mismatch", "$.controllerProfile.displayRef",
                   "ControllerProfile 与 DisplayProfile revision 不一致")
        expected_controller = f"{controller.get('id')}@{controller.get('revision')}"
        if target.get("controllerProfileRef") != expected_controller:
            _issue(issues, "controller-ref-mismatch", "$.buildTarget.controllerProfileRef",
                   "BuildTarget 与 ControllerProfile revision 不一致")


def validate_project_document(doc: Any) -> dict[str, Any]:
    """Validate a project document or raise ``ProjectDocumentValidationError``."""

    issues: list[dict[str, str]] = []
    if not isinstance(doc, dict):
        raise ProjectDocumentValidationError([
            {"code": "document-type", "path": "$", "message": "工程文档必须是 JSON 对象"},
        ])

    try:
        size = len(json.dumps(doc, ensure_ascii=False, separators=(",", ":")).encode("utf-8"))
    except (TypeError, ValueError) as exc:
        raise ProjectDocumentValidationError([
            {"code": "document-json", "path": "$", "message": f"工程文档不能编码为 JSON: {exc}"},
        ]) from exc
    if size > MAX_DOCUMENT_BYTES:
        _issue(issues, "document-size", "$",
               f"工程文档大小 {size} bytes 超过限制 {MAX_DOCUMENT_BYTES} bytes")

    _scan_trust(doc, issues)
    if any(issue["code"] in {"document-size", "document-depth"} for issue in issues):
        raise ProjectDocumentValidationError(issues)

    version = doc.get("schemaVersion")
    kind = doc.get("kind")
    if kind == "lvgl-project-snapshot":
        _validate_snapshot(doc, issues)
    elif version == 2 and kind == "lvgl-ui-project":
        if _append_schema_issues("ui.schema.json", doc, issues):
            _validate_v2_semantics(doc, issues)
    elif version == 1 and kind is None:
        _validate_v1(doc, issues)
    else:
        _issue(issues, "unsupported-format", "$",
               "仅接受 UiProject schemaVersion=2；schemaVersion=1 只作为迁移兼容格式")

    if issues:
        raise ProjectDocumentValidationError(issues)
    return doc


def validate_catalog_document(doc: Any, expected_kind: str | None = None) -> dict[str, Any]:
    """Validate a revisioned Profile or BuildTarget catalogue document."""

    issues: list[dict[str, str]] = []
    if not isinstance(doc, dict):
        raise ProjectDocumentValidationError([
            {"code": "document-type", "path": "$", "message": "catalog document must be a JSON object"},
        ])

    try:
        size = len(json.dumps(doc, ensure_ascii=False, separators=(",", ":")).encode("utf-8"))
    except (TypeError, ValueError) as exc:
        raise ProjectDocumentValidationError([
            {"code": "document-json", "path": "$", "message": f"catalog document is not JSON encodable: {exc}"},
        ]) from exc
    if size > MAX_DOCUMENT_BYTES:
        _issue(issues, "document-size", "$", f"catalog document exceeds {MAX_DOCUMENT_BYTES} bytes")

    _scan_trust(doc, issues)
    kind = doc.get("kind")
    if expected_kind is not None and kind != expected_kind:
        _issue(issues, "kind-mismatch", "$.kind", f"expected {expected_kind!r}, got {kind!r}")
    schema_name = CATALOG_SCHEMAS.get(kind)
    if schema_name is None:
        _issue(issues, "unsupported-kind", "$.kind", f"unsupported catalog kind {kind!r}")
    else:
        _append_schema_issues(schema_name, doc, issues)

    prefix = CATALOG_ID_PREFIXES.get(kind)
    object_id = doc.get("id")
    if prefix is not None and (
        not isinstance(object_id, str)
        or re.fullmatch(rf"{re.escape(prefix)}:[a-z0-9][a-z0-9._-]*", object_id) is None
    ):
        _issue(issues, "bad-catalog-id", "$.id", f"id must match {prefix}:<lowercase-slug>")

    if kind == "lvgl-build-target":
        ui_ref = doc.get("uiProjectRef")
        theme_ref = doc.get("themeRef")
        if (
            isinstance(ui_ref, str)
            and isinstance(theme_ref, str)
            and not theme_ref.startswith(f"{ui_ref}#theme:")
            and re.fullmatch(r"theme:[a-z0-9][a-z0-9._-]*@[1-9]\d*", theme_ref) is None
        ):
            _issue(issues, "theme-ref-mismatch", "$.themeRef", "themeRef must belong to uiProjectRef")

    def positive_size(value: Any, path: str) -> None:
        if not isinstance(value, dict):
            return
        for field in ("width", "height"):
            amount = value.get(field)
            if isinstance(amount, (int, float)) and not isinstance(amount, bool) and amount <= 0:
                _issue(issues, "non-positive-size", f"{path}.{field}", f"{field} must be greater than zero")

    if kind == "display-profile":
        positive_size(doc.get("logicalSize"), "$.logicalSize")
        positive_size(doc.get("visibleRect"), "$.visibleRect")
    elif kind == "controller-profile":
        frame = doc.get("frame")
        if isinstance(frame, dict):
            positive_size(frame.get("viewBox"), "$.frame.viewBox")
            positive_size(frame.get("screenViewport"), "$.frame.screenViewport")
    elif kind == "input-profile":
        positive_size(doc.get("rawSize"), "$.rawSize")
    elif kind == "firmware-profile":
        target = doc.get("target")
        if isinstance(target, str) and re.fullmatch(r"[a-z0-9][a-z0-9._-]*", target) is None:
            _issue(issues, "bad-firmware-target", "$.target", "target must be a lowercase stable identifier")
        lv_conf = doc.get("lvConf")
        if isinstance(lv_conf, dict):
            for key in lv_conf:
                if re.fullmatch(r"LV_[A-Z0-9_]+", key) is None:
                    _issue(issues, "bad-lv-conf-key", f"$.lvConf.{key}", "lvConf keys must match LV_[A-Z0-9_]+")
        for field in ("supportedWidgets", "supportedSubjects", "supportedActions"):
            values = doc.get(field)
            if isinstance(values, list) and len(values) != len(set(values)):
                _issue(issues, "duplicate-firmware-capability", f"$.{field}", f"{field} must not contain duplicates")
    elif kind == "lvgl-theme":
        tokens = doc.get("tokens")
        if isinstance(tokens, list):
            token_ids = [token.get("id") for token in tokens if isinstance(token, dict)]
            if len(token_ids) != len(set(token_ids)):
                _issue(issues, "duplicate-token", "$.tokens", "theme token ids must be unique")
            for index, token_id in enumerate(token_ids):
                if not isinstance(token_id, str) or re.fullmatch(r"[a-z][a-z0-9]*(\.[a-z0-9]+)*", token_id) is None:
                    _issue(issues, "bad-token-id", f"$.tokens[{index}].id", "token id must be a dotted lowercase semantic id")

    if issues:
        raise ProjectDocumentValidationError(issues)
    return doc
