/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_lot(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_lottie_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "lot");
    #endif
    static uint8_t lottie_buf_1[64 * 64 * 4];   /* ARGB8888 渲染缓冲 */
    lv_lottie_set_buffer(obj, 64, 64, lottie_buf_1);
    /* TODO: 提供动画数据符号(如 xxd -i anim_ok.json 生成,符号名改成下面两个) */
    extern const uint8_t lottie_anim_ok[];
    extern const size_t lottie_anim_ok_size;
    lv_lottie_set_src_data(obj, lottie_anim_ok, lottie_anim_ok_size);
    lv_obj_set_width(obj, 64);
    lv_obj_set_height(obj, 64);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.lot = create_lot(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
