/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_btn(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn");
    #endif
    return obj;
}

static lv_obj_t * create_btn_2(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_2");
    #endif
    lv_obj_set_x(obj, 50);
    return obj;
}

static lv_obj_t * create_btn_3(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_3");
    #endif
    lv_obj_set_x(obj, 100);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.btn = create_btn(root);
    ui_main.btn_2 = create_btn_2(root);
    ui_main.btn_3 = create_btn_3(root);

    lv_obj_t * label_1 = lv_label_create(root);
    lv_label_set_text(label_1, "anon");
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
