/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_tvw(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_tileview_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "tvw");
    #endif
    lv_obj_set_width(obj, lv_pct(100));
    lv_obj_set_height(obj, lv_pct(100));

    lv_obj_t * tileview_tile_1 = lv_tileview_add_tile(obj, 0, 0, LV_DIR_HOR);

    lv_obj_t * label_2 = lv_label_create(tileview_tile_1);
    lv_obj_set_align(label_2, LV_ALIGN_CENTER);
    lv_label_set_text(label_2, "Tile 0,0");

    lv_obj_t * tileview_tile_3 = lv_tileview_add_tile(obj, 1, 0, LV_DIR_ALL);

    lv_obj_t * label_4 = lv_label_create(tileview_tile_3);
    lv_obj_set_align(label_4, LV_ALIGN_CENTER);
    lv_label_set_text(label_4, "Tile 1,0");
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.tvw = create_tvw(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
