/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_anim(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_animimg_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "anim");
    #endif
    static const void * srcs_1[] = {&img_f1, &img_f2};
    lv_animimg_set_src(obj, srcs_1, 2);
    lv_animimg_set_duration(obj, 500);
    lv_animimg_set_repeat_count(obj, 3);
    lv_animimg_start(obj);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.anim = create_anim(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
