/* styles.c — GENERATED by lvgl-web-designer — do not edit */
#include "styles.h"

lv_style_t style_s_title;

void ui_styles_init(void)
{
    static bool inited = false;
    if(inited) return;
    inited = true;

    lv_style_init(&style_s_title);
    lv_style_set_text_font(&style_s_title, &lv_font_montserrat_16);
    lv_style_set_text_color(&style_s_title, lv_color_hex(0xe0e6f0));
}
