/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_lbl_title(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_label_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "lbl_title");
    #endif
    lv_label_set_text(obj, "Target demo");
    lv_obj_add_style(obj, &style_s_title, 0);
    return obj;
}

static lv_obj_t * create_btn_go(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_go");
    #endif
    lv_obj_set_width(obj, 100);
    lv_obj_set_height(obj, 40);
    lv_obj_add_event_cb(obj, on_go, LV_EVENT_CLICKED, NULL);

    lv_obj_t * label_1 = lv_label_create(obj);
    lv_label_set_text(label_1, "GO");
    return obj;
}

static lv_obj_t * create_sld_v(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_slider_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "sld_v");
    #endif
    lv_obj_set_width(obj, 150);
    lv_obj_set_height(obj, 10);
    lv_slider_set_value(obj, 30, LV_ANIM_OFF);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    ui_main.lbl_title = create_lbl_title(root);
    ui_main.btn_go = create_btn_go(root);
    ui_main.sld_v = create_sld_v(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
