/* objects.h — GENERATED by lvgl-web-designer — do not edit */
#pragma once
#include "ui_conf.h"

typedef struct {
    lv_obj_t * root;
    lv_obj_t * arc_vol;
    lv_obj_t * lbl_vol;
    lv_obj_t * sw_mute;
    lv_obj_t * btn_up;
    lv_obj_t * btn_reset;
    lv_obj_t * btn_settings;
} ui_main_t;

extern ui_main_t ui_main;   /* 屏幕未创建时字段为 NULL */

typedef struct {
    lv_obj_t * root;
    lv_obj_t * lbl_msg;
    lv_obj_t * btn_back;
} ui_settings_t;

extern ui_settings_t ui_settings;   /* 屏幕未创建时字段为 NULL */
