/* subjects.c — GENERATED by lvgl-web-designer — do not edit */
#include "subjects.h"

lv_subject_t subject_volume;
lv_subject_t subject_muted;
lv_subject_t subject_msg;
lv_subject_t subject_accent_c;
static char subject_msg_buf[64];
static char subject_msg_prev_buf[64];

void ui_subjects_init(void)
{
    static bool inited = false;
    if(inited) return;
    inited = true;

    lv_subject_init_int(&subject_volume, 30);
    lv_subject_set_min_value_int(&subject_volume, 0);
    lv_subject_set_max_value_int(&subject_volume, 100);
    lv_subject_init_int(&subject_muted, 0);
    lv_subject_init_string(&subject_msg, subject_msg_buf, subject_msg_prev_buf, sizeof(subject_msg_buf), "hi");
    lv_subject_init_color(&subject_accent_c, lv_color_hex(0xff8800));
}
