/* subjects.h — GENERATED by lvgl-web-designer — do not edit */
#pragma once
#include "ui_conf.h"

extern lv_subject_t subject_volume;
extern lv_subject_t subject_muted;
extern lv_subject_t subject_msg;
extern lv_subject_t subject_accent_c;

void ui_subjects_init(void);
