/* ui.c — GENERATED by lvgl-web-designer — do not edit */
#include "ui.h"

void ui_init(void)
{
    ui_styles_init();
    ui_subjects_init();
    lv_screen_load(ui_main_create());
}

void ui_deinit(void)
{
    ui_main_destroy();
    ui_settings_destroy();
}
