/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_btn_cancel(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_msgbox_add_footer_button(parent, "Cancel");
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_cancel");
    #endif
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x802020), 0);
    return obj;
}

static lv_obj_t * create_mb(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_msgbox_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "mb");
    #endif
    lv_obj_set_width(obj, 200);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_msgbox_add_title(obj, "Notice");
    lv_msgbox_add_text(obj, "Save changes?");
    lv_msgbox_add_close_button(obj);

    lv_msgbox_add_footer_button(obj, "OK");
    ui_main.btn_cancel = create_btn_cancel(obj);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.mb = create_mb(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
