/* actions_default.c — GENERATED by lvgl-web-designer — do not edit;weak 空实现兜底 */
#include "actions.h"

#ifndef UI_NO_WEAK   /* 无 weak 的编译器:兜底停用,回调须在 actions.c 全部实现 */

UI_WEAK void on_go(lv_event_t * e) { LV_UNUSED(e); }

#endif /* !UI_NO_WEAK */
