/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_tbl(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_table_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "tbl");
    #endif
    lv_table_set_column_count(obj, 3);
    lv_table_set_row_count(obj, 3);

    lv_table_set_column_width(obj, 0, 60);

    lv_table_set_column_width(obj, 2, 90);

    lv_table_set_cell_value(obj, 0, 0, "Name");

    lv_table_set_cell_value(obj, 0, 1, "Qty");
    lv_table_set_cell_ctrl(obj, 0, 1, LV_TABLE_CELL_CTRL_MERGE_RIGHT | LV_TABLE_CELL_CTRL_TEXT_CROP);

    lv_table_set_cell_value(obj, 1, 0, "Apple");

    lv_table_set_cell_value(obj, 1, 1, "3");

    lv_table_set_cell_value(obj, 2, 2, "total: 3");
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.tbl = create_tbl(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
