/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_sp(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_spinner_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "sp");
    #endif
    lv_obj_set_width(obj, 100);
    lv_obj_set_height(obj, 100);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_spinner_set_anim_params(obj, 800, 200);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.sp = create_sp(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
