/* screens/main.c — GENERATED by lvgl-web-designer — do not edit */
#include "../ui.h"

ui_main_t ui_main;

static lv_obj_t * create_panel(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_obj_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "panel");
    #endif
    lv_obj_set_width(obj, 240);
    lv_obj_set_height(obj, 320);
    return obj;
}

static lv_obj_t * create_title(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_label_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "title");
    #endif
    lv_obj_set_y(obj, 4);
    lv_obj_set_width(obj, LV_SIZE_CONTENT);
    lv_obj_set_height(obj, LV_SIZE_CONTENT);
    lv_obj_set_align(obj, LV_ALIGN_TOP_MID);
    lv_label_set_text(obj, "Hello & <World>");
    lv_label_set_long_mode(obj, LV_LABEL_LONG_MODE_DOTS);
    return obj;
}

static lv_obj_t * create_btn_ok(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_button_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "btn_ok");
    #endif
    lv_obj_set_width(obj, 100);
    lv_obj_set_height(obj, 40);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_set_flag(obj, LV_OBJ_FLAG_HIDDEN, false);
    lv_obj_set_flag(obj, LV_OBJ_FLAG_CHECKABLE, true);
    lv_obj_set_state(obj, LV_STATE_CHECKED, true);

    lv_obj_t * label_1 = lv_label_create(obj);
    lv_obj_set_align(label_1, LV_ALIGN_CENTER);
    lv_label_set_text(label_1, "OK");
    return obj;
}

static lv_obj_t * create_sld(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_slider_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "sld");
    #endif
    lv_obj_set_width(obj, 150);
    lv_obj_set_height(obj, 10);
    lv_slider_set_min_value(obj, 10);
    lv_slider_set_value(obj, 35, LV_ANIM_ON);
    lv_slider_set_start_value(obj, 20, LV_ANIM_OFF);
    lv_slider_set_mode(obj, LV_SLIDER_MODE_RANGE);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xff0000), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_radius(obj, 2, LV_PART_KNOB | LV_STATE_PRESSED);
    return obj;
}

static lv_obj_t * create_sw(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_switch_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "sw");
    #endif
    lv_obj_set_width(obj, 50);
    lv_obj_set_height(obj, 25);
    lv_switch_set_orientation(obj, LV_SWITCH_ORIENTATION_HORIZONTAL);
    return obj;
}

static lv_obj_t * create_cb(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_checkbox_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "cb");
    #endif
    lv_checkbox_set_text(obj, "Agree");
    return obj;
}

static lv_obj_t * create_bar_dl(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_bar_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "bar_dl");
    #endif
    lv_obj_set_width(obj, 150);
    lv_obj_set_height(obj, 15);
    lv_bar_set_value(obj, 66, LV_ANIM_OFF);
    lv_bar_set_max_value(obj, 200);
    return obj;
}

static lv_obj_t * create_arc_vol(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_arc_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "arc_vol");
    #endif
    lv_obj_set_width(obj, 150);
    lv_obj_set_height(obj, 150);
    lv_arc_set_rotation(obj, 90);
    lv_arc_set_value(obj, 40);
    lv_arc_set_mode(obj, LV_ARC_MODE_REVERSE);
    return obj;
}

static lv_obj_t * create_img_logo(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_image_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "img_logo");
    #endif
    lv_image_set_src(obj, &img_logo);
    lv_image_set_rotation(obj, 450);
    lv_image_set_scale_x(obj, 512);
    lv_image_set_pivot_x(obj, lv_pct(50));
    lv_image_set_pivot_y(obj, 30);
    return obj;
}

static lv_obj_t * create_dd(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_dropdown_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "dd");
    #endif
    lv_obj_set_width(obj, 130);
    lv_obj_set_height(obj, LV_SIZE_CONTENT);
    lv_dropdown_set_options(obj, "Red\nGreen\nBlue");
    lv_dropdown_set_selected(obj, 1);

    lv_obj_t * dropdown_list_1 = lv_dropdown_get_list(obj);
    lv_obj_set_style_bg_color(dropdown_list_1, lv_color_hex(0x202020), 0);
    return obj;
}

static lv_obj_t * create_rl(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_roller_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "rl");
    #endif
    lv_roller_set_selected(obj, 2, LV_ANIM_ON);
    lv_roller_set_visible_row_count(obj, 4);
    lv_roller_set_options(obj, "One\nTwo\nThree", LV_ROLLER_MODE_INFINITE);
    return obj;
}

static lv_obj_t * create_ta(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_textarea_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "ta");
    #endif
    lv_obj_set_width(obj, 150);
    lv_obj_set_height(obj, 70);
    lv_textarea_set_placeholder_text(obj, "Type…");
    lv_textarea_set_one_line(obj, true);
    lv_textarea_set_max_length(obj, 32);
    return obj;
}

static lv_obj_t * create_spin(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_spinbox_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "spin");
    #endif
    lv_obj_set_width(obj, 100);
    lv_obj_set_height(obj, 40);
    lv_spinbox_set_value(obj, 7);
    lv_spinbox_set_rollover(obj, true);
    lv_spinbox_set_digit_count(obj, 3);
    lv_spinbox_set_step(obj, 10);
    return obj;
}

static lv_obj_t * create_qr(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_qrcode_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "qr");
    #endif
    lv_qrcode_set_size(obj, 100);
    lv_qrcode_set_dark_color(obj, lv_color_hex(0x003a57));
    lv_qrcode_update(obj, "https://lvgl.io", lv_strlen("https://lvgl.io"));
    lv_qrcode_set_quiet_zone(obj, true);
    return obj;
}

static lv_obj_t * create_sc(lv_obj_t * parent)
{
    lv_obj_t * obj = lv_scale_create(parent);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(obj, "sc");
    #endif
    lv_obj_set_width(obj, 200);
    lv_obj_set_height(obj, 100);
    lv_scale_set_mode(obj, LV_SCALE_MODE_ROUND_INNER);
    lv_scale_set_total_tick_count(obj, 21);
    lv_scale_set_label_show(obj, false);
    lv_scale_set_angle_range(obj, 240);
    lv_scale_set_rotation(obj, 120);
    return obj;
}

lv_obj_t * ui_main_create(void)
{
    if(ui_main.root) return ui_main.root;

    lv_obj_t * root = lv_obj_create(NULL);
    ui_main.root = root;
    lv_obj_set_width(root, 240);
    lv_obj_set_height(root, 320);
    #if LV_USE_OBJ_NAME
    lv_obj_set_name(root, "main");
    #endif
    ui_main.panel = create_panel(root);
    ui_main.title = create_title(root);
    ui_main.btn_ok = create_btn_ok(root);
    ui_main.sld = create_sld(root);
    ui_main.sw = create_sw(root);
    ui_main.cb = create_cb(root);
    ui_main.bar_dl = create_bar_dl(root);
    ui_main.arc_vol = create_arc_vol(root);
    ui_main.img_logo = create_img_logo(root);
    ui_main.dd = create_dd(root);
    ui_main.rl = create_rl(root);
    ui_main.ta = create_ta(root);
    ui_main.spin = create_spin(root);
    ui_main.qr = create_qr(root);
    ui_main.sc = create_sc(root);
    return root;
}

void ui_main_destroy(void)
{
    if(!ui_main.root) return;
    lv_obj_delete(ui_main.root);
    lv_memzero(&ui_main, sizeof(ui_main));
}
